// theme/angular/demo2/src/app/_metronic/partials/content/widgets/lists/lists-widget1/lists-widget1.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-lists-widget1',
  templateUrl: './lists-widget1.component.html',
})
export class ListsWidget1Component implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<div class="card card-custom card-stretch gutter-b">
  <!-- Header -->
  <div class="card-header border-0 mt-4">
    <h3 class="card-title align-items-start flex-column">
      <span class="card-label font-weight-bolder text-dark"
        >Tasks Overview</span
      >
      <span class="text-muted mt-3 font-weight-bold font-size-sm"
        >Pending 10 tasks</span
      >
    </h3>
    <div class="card-toolbar">
      <div
        ngbDropdown
        placement="bottom-right"
        class="dropdown dropdown-inline"
        title="Quick actions"
      >
        <a
          ngbDropdownToggle
          class="btn btn-clean btn-hover-light-primary btn-sm btn-icon"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          <i class="ki ki-bold-more-hor"></i>
        </a>
        <div
          ngbDropdownMenu
          class="dropdown-menu dropdown-menu-md dropdown-menu-right"
        >
          <app-dropdown-menu4></app-dropdown-menu4>
        </div>
      </div>
    </div>
  </div>
  <!-- Body -->
  <div class="card-body pt-8">
    <!--begin::Item-->
    <div class="d-flex align-items-center mb-10">
      <!--begin::Symbol-->
      <div class="symbol symbol-40 symbol-light-primary mr-5">
        <span class="symbol-label">
          <span
            [inlineSVG]="'./assets/media/svg/icons/Home/Library.svg'"
            class="svg-icon svg-icon-lg svg-icon-primary"
          ></span>
        </span>
      </div>
      <!--end::Symbol-->

      <!--begin::Text-->
      <div class="d-flex flex-column font-weight-bold">
        <a class="text-dark text-hover-primary mb-1 font-size-lg cursor-pointer"
          >Project Briefing</a
        >
        <span class="text-muted">Project Manager</span>
      </div>
      <!--end::Text-->
    </div>
    <!--end::Item-->

    <!--begin::Item-->
    <div class="d-flex align-items-center mb-10">
      <!--begin::Symbol-->
      <div class="symbol symbol-40 symbol-light-warning mr-5">
        <span class="symbol-label">
          <span
            [inlineSVG]="'./assets/media/svg/icons/Communication/Write.svg'"
            class="svg-icon svg-icon-lg svg-icon-warning"
          ></span>
        </span>
      </div>
      <!--end::Symbol-->

      <!--begin::Text-->
      <div class="d-flex flex-column font-weight-bold">
        <a
          class="text-dark-75 text-hover-primary mb-1 font-size-lg cursor-pointer"
          >Concept Design</a
        >
        <span class="text-muted">Art Director</span>
      </div>
      <!--end::Text-->
    </div>
    <!--end::Item-->

    <!--begin::Item-->
    <div class="d-flex align-items-center mb-10">
      <!--begin::Symbol-->
      <div class="symbol symbol-40 symbol-light-success mr-5">
        <span class="symbol-label">
          <span
            [inlineSVG]="
              './assets/media/svg/icons/Communication/Group-chat.svg'
            "
            class="svg-icon svg-icon-lg svg-icon-success"
          ></span>
        </span>
      </div>
      <!--end::Symbol-->

      <!--begin::Text-->
      <div class="d-flex flex-column font-weight-bold">
        <a class="text-dark text-hover-primary mb-1 font-size-lg cursor-pointer"
          >Functional Logics</a
        >
        <span class="text-muted">Lead Developer</span>
      </div>
      <!--end::Text-->
    </div>
    <!--end::Item-->

    <!--begin::Item-->
    <div class="d-flex align-items-center mb-10">
      <!--begin::Symbol-->
      <div class="symbol symbol-40 symbol-light-danger mr-5">
        <span class="symbol-label">
          <span
            [inlineSVG]="'./assets/media/svg/icons/General/Attachment2.svg'"
            class="svg-icon svg-icon-lg svg-icon-danger"
          ></span>
        </span>
      </div>
      <!--end::Symbol-->

      <!--begin::Text-->
      <div class="d-flex flex-column font-weight-bold">
        <a class="text-dark text-hover-primary mb-1 font-size-lg cursor-pointer"
          >Development</a
        >
        <span class="text-muted">DevOps</span>
      </div>
      <!--end::Text-->
    </div>
    <!--end::Item-->

    <!--begin::Item-->
    <div class="d-flex align-items-center mb-2">
      <!--begin::Symbol-->
      <div class="symbol symbol-40 symbol-light-info mr-5">
        <span class="symbol-label">
          <span
            [inlineSVG]="
              './assets/media/svg/icons/Communication/Shield-user.svg'
            "
            class="svg-icon svg-icon-lg svg-icon-info"
          ></span>
        </span>
      </div>
      <!--end::Symbol-->

      <!--begin::Text-->
      <div class="d-flex flex-column font-weight-bold">
        <a class="text-dark text-hover-primary mb-1 font-size-lg cursor-pointer"
          >Testing</a
        >
        <span class="text-muted">QA Managers</span>
      </div>
      <!--end::Text-->
    </div>
    <!--end::Item-->
  </div>
</div>

// theme/react/demo2/src/_metronic/_partials/widgets/lists/ListsWidget1.js
/* eslint-disable no-script-url,jsx-a11y/anchor-is-valid */
import React from "react";
import SVG from "react-inlinesvg";
import {Dropdown} from "react-bootstrap";
import {toAbsoluteUrl} from "../../../_helpers";
import {DropdownCustomToggler, DropdownMenu4} from "../../dropdowns";

export function ListsWidget1({ className }) {
  return (
    <>
      <div className={`card card-custom ${className}`}>
        {/* Header */}
        <div className="card-header border-0">
          <h3 className="card-title font-weight-bolder text-dark">
            Tasks Overview
          </h3>
          <div className="card-toolbar">
            <Dropdown className="dropdown-inline" alignRight>
              <Dropdown.Toggle
                className="btn btn-clean btn-hover-light-primary btn-sm btn-icon"
                variant="transparent"
                id="dropdown-toggle-top"
                as={DropdownCustomToggler}
               >
                <i className="ki ki-bold-more-hor" />
              </Dropdown.Toggle>
              <Dropdown.Menu className="dropdown-menu dropdown-menu-sm dropdown-menu-right">
                <DropdownMenu4 />
              </Dropdown.Menu>
            </Dropdown>            
          </div>
        </div>

        {/* Body */}
        <div className="card-body pt-2">
          <div className="d-flex align-items-center mb-10">
            <div className="symbol symbol-40 symbol-light-primary mr-5">
              <span className="symbol-label">
                <span className="svg-icon svg-icon-lg svg-icon-primary">
                  <SVG
                    className="h-75 align-self-end"
                    src={toAbsoluteUrl("/media/svg/icons/Home/Library.svg")}
                  ></SVG>
                </span>
              </span>
            </div>

            <div className="d-flex flex-column font-weight-bold">
              <a
                href="#"
                className="text-dark text-hover-primary mb-1 font-size-lg"
              >
                Project Briefing
              </a>
              <span className="text-muted">Project Manager</span>
            </div>
          </div>

          <div className="d-flex align-items-center mb-10">
            <div className="symbol symbol-40 symbol-light-warning mr-5">
              <span className="symbol-label">
                <span className="svg-icon svg-icon-lg svg-icon-warning">
                  <SVG
                    className="h-75 align-self-end"
                    src={toAbsoluteUrl(
                      "/media/svg/icons/Communication/Write.svg"
                    )}
                  ></SVG>
                </span>
              </span>
            </div>
            <div className="d-flex flex-column font-weight-bold">
              <a
                href="#"
                className="text-dark-75 text-hover-primary mb-1 font-size-lg"
              >
                Concept Design
              </a>
              <span className="text-muted">Art Director</span>
            </div>
          </div>
          <div className="d-flex align-items-center mb-10">
            <div className="symbol symbol-40 symbol-light-success mr-5">
              <span className="symbol-label">
                <span className="svg-icon svg-icon-lg svg-icon-success">
                  <SVG
                    className="h-75 align-self-end"
                    src={toAbsoluteUrl(
                      "/media/svg/icons/Communication/Group-chat.svg"
                    )}
                  ></SVG>
                </span>
              </span>
            </div>

            <div className="d-flex flex-column font-weight-bold">
              <a
                href="#"
                className="text-dark text-hover-primary mb-1 font-size-lg"
              >
                Functional Logics
              </a>
              <span className="text-muted">Lead Developer</span>
            </div>
          </div>

          <div className="d-flex align-items-center mb-10">
            <div className="symbol symbol-40 symbol-light-danger mr-5">
              <span className="symbol-label">
                <span className="svg-icon svg-icon-lg svg-icon-danger">
                  <SVG
                    className="h-75 align-self-end"
                    src={toAbsoluteUrl(
                      "/media/svg/icons/General/Attachment2.svg"
                    )}
                  ></SVG>
                </span>
              </span>
            </div>

            <div className="d-flex flex-column font-weight-bold">
              <a
                href="#"
                className="text-dark text-hover-primary mb-1 font-size-lg"
              >
                Development
              </a>
              <span className="text-muted">DevOps</span>
            </div>
          </div>

          <div className="d-flex align-items-center mb-2">
            <div className="symbol symbol-40 symbol-light-info mr-5">
              <span className="symbol-label">
                <span className="svg-icon svg-icon-lg  svg-icon-info">
                  <SVG
                    className="h-75 align-self-end"
                    src={toAbsoluteUrl(
                      "/media/svg/icons/Communication/Shield-user.svg"
                    )}
                  ></SVG>
                </span>
              </span>
            </div>

            <div className="d-flex flex-column font-weight-bold">
              <a
                href="#"
                className="text-dark text-hover-primary mb-1 font-size-lg"
              >
                Testing
              </a>
              <span className="text-muted">QA Managers</span>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
