// theme/react/demo3/src/_metronic/_partials/builder/Builder.js
/* eslint-disable no-script-url,jsx-a11y/anchor-is-valid,jsx-a11y/img-redundant-alt */
import React, { useMemo, useState } from "react";
import { Formik } from "formik";
import { get, merge } from "lodash";
import { FormHelperText, Switch } from "@material-ui/core";
import clsx from "clsx";
// https://github.com/conorhastings/react-syntax-highlighter#prism
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
// See https://github.com/PrismJS/prism-themes
import { coy as highlightStyle } from "react-syntax-highlighter/dist/esm/styles/prism";
import {
  useHtmlClassService,
  setLayoutConfig,
  getInitLayoutConfig,
} from "../../layout";
import { Card, CardBody, CardHeader, Notice } from "../controls";

const localStorageActiveTabKey = "builderActiveTab";

export function Builder() {
  const activeTab = localStorage.getItem(localStorageActiveTabKey);
  const [key, setKey] = useState(activeTab ? +activeTab : 0);
  const [isLoading, setIsLoading] = useState(false);
  const htmlClassService = useHtmlClassService();
  const initialValues = useMemo(
    () =>
      merge(
        // Fulfill changeable fields.
        getInitLayoutConfig(),
        htmlClassService.config
      ),
    [htmlClassService.config]
  );

  const saveCurrentTab = (_tab) => {
    localStorage.setItem(localStorageActiveTabKey, _tab);
  };

  return (
    <>
      <Notice svg="/media/svg/icons/Tools/Compass.svg">
        <p>
          The layout builder is to assist your set and configure your preferred
          project layout specifications and preview it in real time. The
          configured layout options will be saved until you change or reset
          them. To use the layout builder, choose the layout options and click
          the <code>Preview</code> button to preview the changes.
        </p>
      </Notice>
      {/*Formic off site: https://jaredpalmer.com/formik/docs/overview*/}
      <Formik
        initialValues={initialValues}
        onSubmit={(values) => {
          setIsLoading(true);
          setLayoutConfig(values);
        }}
        onReset={() => {
          setIsLoading(true);
          setLayoutConfig(getInitLayoutConfig());
        }}
      >
        {({ values, handleReset, handleSubmit, handleChange, handleBlur }) => (
          <>
            <div className="card card-custom">
              {/*Header*/}
              <div className="card-header card-header-tabs-line">
                <ul
                  className="nav nav-dark nav-bold nav-tabs nav-tabs-line"
                  data-remember-tab="tab_id"
                  role="tablist"
                >
                  <li className="nav-item">
                    <a
                      className={`nav-link ${key === 0 ? "active" : ""}`}
                      data-toggle="tab"
                      onClick={() => {
                        setKey(0);
                        saveCurrentTab(0);
                      }}
                    >
                      Mobile Header
                    </a>
                  </li>
                  <li className="nav-item">
                    <a
                      className={`nav-link ${key === 1 ? "active" : ""}`}
                      data-toggle="tab"
                      onClick={() => {
                        setKey(1);
                        saveCurrentTab(1);
                      }}
                    >
                      Subheader
                    </a>
                  </li>
                  <li className="nav-item">
                    <a
                      className={`nav-link ${key === 2 ? "active" : ""}`}
                      data-toggle="tab"
                      onClick={() => {
                        setKey(2);
                        saveCurrentTab(2);
                      }}
                    >
                      Content
                    </a>
                  </li>
                  <li className="nav-item">
                    <a
                      className={`nav-link ${key === 3 ? "active" : ""}`}
                      data-toggle="tab"
                      onClick={() => {
                        setKey(3);
                        saveCurrentTab(3);
                      }}
                    >
                      Aside
                    </a>
                  </li>
                  <li className="nav-item">
                    <a
                      className={`nav-link ${key === 4 ? "active" : ""}`}
                      data-toggle="tab"
                      onClick={() => {
                        setKey(4);
                        saveCurrentTab(4);
                      }}
                    >
                      Footer
                    </a>
                  </li>
                </ul>
              </div>

              <div className="form">
                <div className="card-body">
                  <div className="tab-content pt-3">
                    <div className={`tab-pane ${key === 0 ? "active" : ""}`}>
                      <div className="form-group row">
                        <label className="col-lg-3 col-form-label text-lg-right">
                          Fixed Header:
                        </label>
                        <div className="col-lg-9 col-xl-4">
                          <Switch
                            onBlur={handleBlur}
                            onChange={handleChange}
                            name="header.self.fixed.mobile"
                            checked={!!get(values, "header.self.fixed.mobile")}
                          />
                          <FormHelperText>
                            Enable fixed header for mobile mode
                          </FormHelperText>
                        </div>
                      </div>
                    </div>
                    <div className={`tab-pane ${key === 1 ? "active" : ""}`}>
                      <div className="form-group row">
                        <label className="col-lg-3 col-form-label text-lg-right">
                          Display Subheader:
                        </label>
                        <div className="col-lg-9 col-xl-4">
                          <Switch
                            onBlur={handleBlur}
                            onChange={handleChange}
                            name="subheader.display"
                            checked={!!get(values, "subheader.display")}
                          />
                          <FormHelperText>Display subheader</FormHelperText>
                        </div>
                      </div>

                      <div className="form-group row">
                        <label className="col-lg-3 col-form-label text-lg-right">
                          Fixed Subheader:
                        </label>
                        <div className="col-lg-9 col-xl-4">
                          <Switch
                            onBlur={handleBlur}
                            onChange={handleChange}
                            name="subheader.fixed"
                            checked={!!get(values, "subheader.fixed")}
                          />
                          <FormHelperText>
                            Enable fixed(sticky) subheader. Requires{" "}
                            <code>Solid</code> subheader style.
                          </FormHelperText>
                        </div>
                      </div>

                      <div className="form-group row">
                        <label className="col-lg-3 col-form-label text-lg-right">
                          Width:
                        </label>
                        <div className="col-lg-9 col-xl-4">
                          <select
                            className="form-control"
                            name="subheader.width"
                            onBlur={handleBlur}
                            value={get(values, "subheader.width")}
                            onChange={handleChange}
                          >
                            <option value="fluid">Fluid</option>
                            <option value="fixed">Fixed</option>
                          </select>
                          <FormHelperText>
                            Select layout width type
                          </FormHelperText>
                        </div>
                      </div>

                      <div className="form-group row">
                        <label className="col-lg-3 col-form-label text-lg-right">
                          Subheader Style:
                        </label>
                        <div className="col-lg-9 col-xl-4">
                          <select
                            className="form-control"
                            name="subheader.style"
                            onBlur={handleBlur}
                            value={get(values, "subheader.style")}
                            onChange={handleChange}
                          >
                            <option value="transparent">Transparent</option>
                            <option value="solid">Solid</option>
                          </select>
                          <FormHelperText>
                            Select subheader style
                          </FormHelperText>
                        </div>
                      </div>
                    </div>
                    <div className={`tab-pane ${key === 2 ? "active" : ""}`}>
                      <div className="form-group row">
                        <label className="col-lg-3 col-form-label text-lg-right">
                          Width:
                        </label>
                        <div className="col-lg-9 col-xl-4">
                          <select
                            className="form-control"
                            name="content.width"
                            onBlur={handleBlur}
                            value={get(values, "content.width")}
                            onChange={handleChange}
                          >
                            <option value="fluid">Fluid</option>
                            <option value="fixed">Fixed</option>
                          </select>
                          <FormHelperText>
                            Select layout width type
                          </FormHelperText>
                        </div>
                      </div>
                    </div>
                    <div className={`tab-pane ${key === 3 ? "active" : ""}`}>
                      <div className="form-group row">
                        <label className="col-lg-3 col-form-label text-lg-right">
                          Display Secondary Panel:
                        </label>
                        <div className="col-lg-9 col-xl-4">
                          <Switch
                            onBlur={handleBlur}
                            onChange={handleChange}
                            name="aside.secondary.display"
                            checked={!!get(values, "aside.secondary.display")}
                          />
                          <FormHelperText>
                            Display aside secondary panel
                          </FormHelperText>
                        </div>
                      </div>

                      <div className="form-group row">
                        <label className="col-lg-3 col-form-label pt-4 text-lg-right">
                          Aside Minimize:
                        </label>
                        <div className="col-lg-9 col-xl-4">
                          <Switch
                            onBlur={handleBlur}
                            onChange={handleChange}
                            name="aside.self.minimize.toggle"
                            checked={
                              !!get(values, "aside.self.minimize.toggle")
                            }
                          />
                          <FormHelperText>
                            Allow aside minimizing
                          </FormHelperText>
                        </div>
                      </div>

                      <div className="form-group row">
                        <label className="col-lg-3 col-form-label pt-4 text-lg-right">
                          Aside Default Minimized:
                        </label>
                        <div className="col-lg-9 col-xl-4">
                          <Switch
                            onBlur={handleBlur}
                            onChange={handleChange}
                            name="aside.self.minimize.default"
                            checked={
                              !!get(values, "aside.self.minimize.default")
                            }
                          />
                          <FormHelperText>
                            Set aside minimized by default
                          </FormHelperText>
                        </div>
                      </div>
                    </div>
                    <div className={`tab-pane ${key === 4 ? "active" : ""}`}>
                    <div className="form-group row">
                        <label className="col-lg-3 col-form-label pt-4 text-lg-right">
                        Fixed Footer:
                        </label>
                        <div className="col-lg-9 col-xl-4">
                          <Switch
                            onBlur={handleBlur}
                            onChange={handleChange}
                            name="footer.fixed"
                            checked={
                              !!get(values, "footer.fixed")
                            }
                          />
                          <FormHelperText>
                          Set fixed footer for desktop mode only
                          </FormHelperText>
                        </div>
                      </div>

                      <div className="form-group row">
                        <label className="col-lg-3 col-form-label text-lg-right">
                          Width:
                        </label>
                        <div className="col-lg-9 col-xl-4">
                          <select
                            className="form-control form-control-solid"
                            name="footer.width"
                            onBlur={handleBlur}
                            value={get(values, "footer.width")}
                            onChange={handleChange}
                          >
                            <option value="fluid">Fluid</option>
                            <option value="fixed">Fixed</option>
                          </select>
                          <FormHelperText>
                            Select layout width type
                          </FormHelperText>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="card-footer">
                  <div className="row">
                    <div className="col-lg-3"></div>
                    <div className="col-lg-9">
                      <button
                        type="button"
                        onClick={handleSubmit}
                        className={`btn btn-primary font-weight-bold mr-2`}
                      >
                        <i className="la la-eye" /> Preview
                      </button>{" "}
                      <button
                        type="button"
                        onClick={handleReset}
                        className={`btn btn-clean font-weight-bold mr-2`}
                      >
                        <i className="la la-recycle" /> Reset
                      </button>{" "}
                      <span
                        className={`ml-3 ${clsx({
                          spinner: isLoading,
                        })}`}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/*Config*/}
            <Card className="mt-4">
              <CardHeader
                title={
                  <>
                    Generated Config{" "}
                    <small>
                      can be used for layout config in{" "}
                      <code>/src/_metronic/layout/LayoutConfig.js</code>
                    </small>
                  </>
                }
              />

              <CardBody>
                <SyntaxHighlighter
                  language="json"
                  style={highlightStyle}
                  customStyle={{
                    background: `none transparent !important`,
                  }}
                >
                  {JSON.stringify(values, null, 2)}
                </SyntaxHighlighter>
              </CardBody>
            </Card>
          </>
        )}
      </Formik>
    </>
  );
}

// theme/angular/demo3/src/app/pages/builder/builder.component.ts
import {
  Component,
  OnInit,
  AfterViewInit,
  ViewChild,
  ElementRef,
} from '@angular/core';
import { NgForm } from '@angular/forms';
import { LayoutService } from '../../_metronic/core/';
import KTLayoutExamples from '../../../assets/js/layout/extended/examples';

@Component({
  selector: 'app-builder',
  templateUrl: './builder.component.html',
  styleUrls: ['./builder.component.scss'],
})
export class BuilderComponent implements OnInit, AfterViewInit {
  model: any;
  @ViewChild('form', { static: true }) form: NgForm;
  activeTabId = 1;
  constructor(private layout: LayoutService, private el: ElementRef) {}

  ngOnInit(): void {
    this.model = this.layout.getConfig();
  }

  setActiveTab(tabId: number) {
    this.activeTabId = tabId;
  }

  getActiveTabCSSClass(tabId: number) {
    if (tabId !== this.activeTabId) {
      return '';
    }

    return 'active';
  }

  resetPreview(): void {
    this.layout.refreshConfigToDefault();
  }

  submitPreview(): void {
    this.layout.setConfig(this.model);
    location.reload();
  }

  ngAfterViewInit() {
    // init code preview examples
    // see /src/assets/js/layout/extended/examples.js
    const elements = this.el.nativeElement.querySelectorAll('.example');
    KTLayoutExamples.init(elements);
  }
}

<app-notice [svg]="'./assets/media/svg/icons/Tools/Tools.svg'">
  <p>
    The layout builder is to assist your set and configure your preferred
    project layout specifications and preview it in real time. The configured
    layout options will be saved until you change or reset them. To use the
    layout builder, choose the layout options and click the
    <code>Preview</code> button to preview the changes.
  </p>
</app-notice>
<!--begin::Card-->
<div class="card card-custom gutter-b">
  <!--begin::Header-->
  <div class="card-header card-header-tabs-line">
    <ul class="nav nav-dark nav-bold nav-tabs nav-tabs-line" role="tablist">
      <li class="nav-item">
        <a
          (click)="setActiveTab(1)"
          class="nav-link cursor-pointer"
          [ngClass]="getActiveTabCSSClass(1)"
          role="tab"
        >
          Mobile Header
        </a>
      </li>
      <li class="nav-item">
        <a
          (click)="setActiveTab(2)"
          class="nav-link cursor-pointer"
          [ngClass]="getActiveTabCSSClass(2)"
          role="tab"
        >
          Subheader
        </a>
      </li>
      <li class="nav-item">
        <a
          (click)="setActiveTab(3)"
          class="nav-link cursor-pointer"
          [ngClass]="getActiveTabCSSClass(3)"
          role="tab"
        >
          Content
        </a>
      </li>
      <li class="nav-item">
        <a
          (click)="setActiveTab(4)"
          class="nav-link cursor-pointer"
          [ngClass]="getActiveTabCSSClass(4)"
          role="tab"
        >
          Aside
        </a>
      </li>
      <li class="nav-item">
        <a
          (click)="setActiveTab(5)"
          class="nav-link cursor-pointer"
          [ngClass]="getActiveTabCSSClass(5)"
          role="tab"
        >
          Footer
        </a>
      </li>
    </ul>
  </div>
  <!--end::Header-->
  <!--begin::Form-->
  <form class="form" novalidate #form="ngForm" (ngSubmit)="submitPreview()">
    <!--begin::Body-->
    <div class="card-body">
      <div class="tab-content pt-3">
        <!-- begin::Header -->
        <div class="tab-pane" [ngClass]="getActiveTabCSSClass(1)">
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Fixed Header:</label
            >
            <div class="col-lg-9 col-xl-4">
              <span class="switch switch-icon">
                <label>
                  <input
                    type="checkbox"
                    name="builder[header][self][fixed][mobile]"
                    [(ngModel)]="model.header.self.fixed.mobile"
                    value="true"
                  />
                  <span></span>
                </label>
              </span>
              <div class="form-text text-muted">
                Enable fixed header for mobile mode
              </div>
            </div>
          </div>
        </div>
        <!-- end::Header -->

        <!-- begin::Subheader -->
        <div class="tab-pane" [ngClass]="getActiveTabCSSClass(2)">
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Display Subheader:</label
            >
            <div class="col-lg-9 col-xl-4">
              <span class="switch switch-icon">
                <label>
                  <input
                    type="checkbox"
                    name="builder[subheader][display]"
                    [(ngModel)]="model.subheader.display"
                    value="true"
                  />
                  <span></span>
                </label>
              </span>
              <div class="form-text text-muted">Display subheader</div>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Fixed Subheader:</label
            >
            <div class="col-lg-9 col-xl-4">
              <span class="switch switch-icon">
                <label>
                  <input
                    type="checkbox"
                    name="builder[subheader][fixed]"
                    [(ngModel)]="model.subheader.fixed"
                    value="true"
                  />
                  <span></span>
                </label>
              </span>
              <div class="form-text text-muted">
                Enable fixed(sticky) subheader. Requires
                <code>Solid</code> subheader style.
              </div>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right">Width:</label>
            <div class="col-lg-9 col-xl-4">
              <select
                class="form-control form-control-solid"
                name="builder[subheader][width]"
                [(ngModel)]="model.subheader.width"
              >
                <option value="fluid">Fluid</option>
                <option value="fixed">Fixed</option>
              </select>
              <div class="form-text text-muted">Select layout width type.</div>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Subheader Style:</label
            >
            <div class="col-lg-9 col-xl-4">
              <select
                class="form-control form-control-solid"
                name="builder[subheader][style]"
                [(ngModel)]="model.subheader.style"
              >
                <option value="transparent">Transparent</option>
                <option value="solid">Solid</option>
              </select>
              <div class="form-text text-muted">Select subheader style</div>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Subheader Layout:</label
            >
            <div class="col-lg-9 col-xl-4">
              <select
                class="form-control form-control-solid"
                name="builder[layout][subheader][layoutVersion]"
                [(ngModel)]="model.subheader.layoutVersion"
              >
                <option value="v1">Subheader 1</option>
                <option value="v2">Subheader 2</option>
                <option value="v3">Subheader 3</option>
                <option value="v4">Subheader 4</option>
                <option value="v5">Subheader 5</option>
                <option value="v6">Subheader 6</option>
              </select>
              <div class="form-text text-muted">Select subheader layout</div>
            </div>
          </div>
        </div>
        <!-- end::Subheader -->

        <!-- begin::Content -->
        <div class="tab-pane" [ngClass]="getActiveTabCSSClass(3)">
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right">Width:</label>
            <div class="col-lg-9 col-xl-4">
              <select
                class="form-control form-control-solid"
                name="builder[content][width]"
                [(ngModel)]="model.content.width"
              >
                <option value="fluid">Fluid</option>
                <option value="fixed">Fixed</option>
              </select>
              <div class="form-text text-muted">Select layout width type.</div>
            </div>
          </div>
        </div>
        <!-- end::Content -->

        <!-- begin::Aside -->
        <div class="tab-pane" [ngClass]="getActiveTabCSSClass(4)">
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Display Secondary Panel:</label
            >
            <div class="col-lg-9 col-xl-6">
              <span class="switch switch-icon">
                <label>
                  <input
                    type="checkbox"
                    name="builder[aside][secondary][display]"
                    [(ngModel)]="model.aside.secondary.display"
                    value="true"
                  />
                  <span></span>
                </label>
              </span>
              <div class="form-text text-muted">
                Display aside secondary panel
              </div>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Minimize:</label
            >
            <div class="col-lg-9 col-xl-4">
              <span class="switch switch-icon">
                <label>
                  <input
                    type="checkbox"
                    name="builde[aside][self][minimize][toggle]"
                    [(ngModel)]="model.aside.self.minimize.toggle"
                    value="true"
                  />
                  <span></span>
                </label>
              </span>
              <div class="form-text text-muted">Allow aside minimizing</div>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Static aside menu:</label
            >
            <div class="col-lg-9 col-xl-6">
              <span class="switch switch-icon">
                <label>
                  <input
                    type="checkbox"
                    name="builder[aside][menu][static]"
                    [(ngModel)]="model.aside.menu.static"
                    value="true"
                  />
                  <span></span>
                </label>
              </span>
              <div class="form-text text-muted">Static aside menu</div>
            </div>
          </div>

          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Default Minimize:</label
            >
            <div class="col-lg-9 col-xl-4">
              <span class="switch switch-icon">
                <label>
                  <input
                    type="checkbox"
                    name="builder[aside][self][minimize][default]"
                    [(ngModel)]="model.aside.self.minimize.default"
                    value="true"
                  />
                  <span></span>
                </label>
              </span>
              <div class="form-text text-muted">
                Set aside minimized by default
              </div>
            </div>
          </div>
        </div>
        <!-- end::Aside -->

        <!-- begin::Footer -->
        <div class="tab-pane" [ngClass]="getActiveTabCSSClass(5)">
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Fixed Desktop Footer:</label
            >
            <div class="col-lg-9 col-xl-4">
              <span class="switch switch-icon">
                <label>
                  <input
                    type="checkbox"
                    name="builder[footer][fixed]"
                    [(ngModel)]="model.footer.fixed"
                    value="true"
                  />
                  <span></span>
                </label>
              </span>
              <div class="form-text text-muted">Set fixed desktop footer</div>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right">Width:</label>
            <div class="col-lg-9 col-xl-4">
              <select
                class="form-control form-control-solid"
                name="builder[footer][width]"
                [(ngModel)]="model.footer.width"
              >
                <option value="fluid">Fluid</option>
                <option value="fixed">Fixed</option>
              </select>
              <div class="form-text text-muted">Select layout width type.</div>
            </div>
          </div>
        </div>
        <!-- end::Footer -->
      </div>
    </div>
    <!--end::Body-->
    <!--begin::Footer-->
    <div class="card-body">
      <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-8">
          <button type="submit" name="builder_submit" class="btn btn-primary">
            Preview
          </button>
          &nbsp;
          <button
            type="submit"
            (click)="resetPreview()"
            name="builder_reset"
            class="btn btn-secondary"
          >
            Reset
          </button>
        </div>
      </div>
    </div>
    <!--end::Footer-->
  </form>
  <!--end::Form-->
</div>
<!--end::Card-->

<div class="card card-custom gutter-b">
  <div class="card-header">
    <div class="card-title">
      <h3 class="card-label">Generated Config</h3>
    </div>
  </div>
  <div class="card-body">
    <!--begin::Example-->
    <div class="example mb-10">
      <p>
        Use for layout config in
        <code>/src/app/_metronic/configs/default-layout.config.ts</code>
      </p>
      <div class="example-code">
        <div class="example-code">
          <span
            class="example-copy"
            data-placement="left"
            ngbTooltip="Copy code"
          ></span>
          <div class="example-highlight">
            <pre><code [highlight]="model|json"></code></pre>
          </div>
        </div>
      </div>
    </div>
    <!--end::Example-->
  </div>
</div>
