// theme/vue/demo3/src/view/pages/Builder.vue
<template>
  <div>
    <!--begin::Notice-->
    <div
      class="alert alert-custom alert-white alert-shadow gutter-b"
      role="alert"
    >
      <div class="alert-icon alert-icon-top">
        <span class="svg-icon svg-icon-3x svg-icon-primary mt-4">
          <!--begin::Svg Icon-->
          <inline-svg src="media/svg/icons/Tools/Tools.svg" />
          <!--end::Svg Icon-->
        </span>
      </div>
      <div class="alert-text">
        <p>
          The layout builder helps to configure the layout with preferred
          options and preview it in real time. The configured layout options
          will be saved until you change or reset them. To use the layout
          builder choose the layout options and click the
          <code>Preview</code> button to preview the changes.
        </p>
        <p>
          <span
            class="label label-inline label-pill label-info label-rounded mr-2"
          >
            INFO:
          </span>
          Some pages from the <code>html</code> version might not exist in the
          <code>vue</code>. But the CSS styles from <code>html</code> version
          already integrated into the <code>vue</code>. All the components from
          the <code>html</code> version are static and non-working components.
          You can copy the component HTML from the <code>html</code> version,
          and paste it in the <code>vue</code> component to get the same style.
          The actual functionality and implementation need to be done by the
          customer because every application has its own business requirements.
        </p>
      </div>
    </div>
    <!--end::Notice-->

    <div class="card card-custom gutter-b">
      <div class="card-header card-header-tabs-line">
        <ul
          class="nav nav-dark nav-bold nav-tabs nav-tabs-line"
          role="tablist"
          ref="builder-tab"
        >
          <li class="nav-item">
            <a
              class="nav-link active"
              v-on:click="setActiveTab"
              data-tab="0"
              data-toggle="tab"
              href="#"
              role="tab"
            >
              Page
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link"
              v-on:click="setActiveTab"
              data-tab="1"
              data-toggle="tab"
              href="#"
              role="tab"
            >
              Mobile Header
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link"
              v-on:click="setActiveTab"
              data-tab="2"
              data-toggle="tab"
              href="#"
              role="tab"
            >
              Subheader
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link"
              v-on:click="setActiveTab"
              data-tab="3"
              data-toggle="tab"
              href="#"
              role="tab"
            >
              Content
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link"
              v-on:click="setActiveTab"
              data-tab="4"
              data-toggle="tab"
              href="#"
              role="tab"
            >
              Aside
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link"
              v-on:click="setActiveTab"
              data-tab="5"
              data-toggle="tab"
              href="#"
              role="tab"
            >
              Footer
            </a>
          </li>
        </ul>
      </div>

      <!--begin::Form-->
      <form class="form" v-on:submit="submit($event)">
        <div class="card-body">
          <b-tabs class="hide-tabs" v-model="tabIndex">
            <b-tab active>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">
                  Page Loader:
                </label>
                <div class="col-lg-9 col-xl-4">
                  <select class="form-control" v-model="config.loader.type">
                    <option value="false">
                      Disabled
                    </option>
                    <option value="spinner-logo" selected="selected">
                      Spinner &amp; Logo
                    </option>
                  </select>
                  <div class="form-text text-muted">
                    Select page loading indicator.
                  </div>
                </div>
              </div>
            </b-tab>

            <b-tab>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">
                  Fixed Header:
                </label>
                <div class="col-lg-9 col-xl-4">
                  <span class="switch switch-icon">
                    <label>
                      <input
                        type="checkbox"
                        v-model="config.header.self.fixed.mobile"
                        value="true"
                        checked=""
                      />
                      <span></span>
                    </label>
                  </span>
                  <div class="form-text text-muted">
                    Enable fixed header for mobile mode
                  </div>
                </div>
              </div>
            </b-tab>

            <b-tab>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">
                  Display Subheader:
                </label>
                <div class="col-lg-9 col-xl-4">
                  <span class="switch switch-icon">
                    <label>
                      <input
                        type="checkbox"
                        v-model="config.subheader.display"
                        value="true"
                        checked=""
                      />
                      <span></span>
                    </label>
                  </span>
                  <div class="form-text text-muted">Display subheader</div>
                </div>
              </div>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">
                  Fixed Subheader:
                </label>
                <div class="col-lg-9 col-xl-4">
                  <span class="switch switch-icon">
                    <label>
                      <input
                        type="checkbox"
                        v-model="config.subheader.fixed"
                        value="true"
                        checked=""
                      />
                      <span></span>
                    </label>
                  </span>
                  <div class="form-text text-muted">
                    Enable fixed(sticky) subheader. Requires Solidsubheader
                    style.
                  </div>
                </div>
              </div>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">Width:</label>
                <div class="col-lg-9 col-xl-4">
                  <select class="form-control" v-model="config.subheader.width">
                    <option value="fluid" selected="">Fluid</option>
                    <option value="fixed">Fixed</option>
                  </select>
                  <div class="form-text text-muted">
                    Select layout width type.
                  </div>
                </div>
              </div>
            </b-tab>

            <b-tab>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">Width:</label>
                <div class="col-lg-9 col-xl-4">
                  <select class="form-control" v-model="config.content.width">
                    <option value="fluid">Fluid</option>
                    <option value="fixed" selected="">Fixed</option>
                  </select>
                  <div class="form-text text-muted">
                    Select layout width type.
                  </div>
                </div>
              </div>
            </b-tab>

            <b-tab>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label"
                  >Display Secondary Panel:</label
                >
                <div class="col-lg-9 col-xl-4">
                  <span class="switch switch-icon">
                    <label>
                      <input
                        type="checkbox"
                        v-model="config.aside.secondary.display"
                        value="true"
                        checked=""
                      />
                      <span></span>
                    </label>
                  </span>
                  <div class="form-text text-muted">
                    Display aside secondary panel
                  </div>
                </div>
              </div>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">Aside Minimize:</label>
                <div class="col-lg-9 col-xl-4">
                  <span class="switch switch-icon">
                    <label>
                      <input
                        type="checkbox"
                        v-model="config.aside.self.minimize.toggle"
                        value="true"
                        checked=""
                      />
                      <span></span>
                    </label>
                  </span>
                  <div class="form-text text-muted">Allow aside minimizing</div>
                </div>
              </div>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label"
                  >Aside Default Minimized:</label
                >
                <div class="col-lg-9 col-xl-4">
                  <span class="switch switch-icon">
                    <label>
                      <input
                        type="checkbox"
                        v-model="config.aside.self.minimize.default"
                        value="true"
                        checked=""
                      />
                      <span></span>
                    </label>
                  </span>
                  <div class="form-text text-muted">
                    Set aside minimized by default
                  </div>
                </div>
              </div>
            </b-tab>

            <b-tab>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">Fixed Footer:</label>
                <div class="col-lg-9 col-xl-4">
                  <span class="switch switch-icon">
                    <label>
                      <input
                        type="checkbox"
                        v-model="config.footer.fixed"
                        value="true"
                        checked=""
                      />
                      <span></span>
                    </label>
                  </span>
                  <div class="form-text text-muted">
                    Set fixed footer for desktop mode only
                  </div>
                </div>
              </div>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">Width:</label>
                <div class="col-lg-9 col-xl-4">
                  <select class="form-control" v-model="config.footer.width">
                    <option value="fluid" selected="">Fluid</option>
                    <option value="fixed">Fixed</option>
                  </select>
                  <div class="form-text text-muted">
                    Select layout width type.
                  </div>
                </div>
              </div>
            </b-tab>
          </b-tabs>
        </div>

        <div class="card-footer">
          <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-9">
              <button type="submit" class="btn btn-primary font-weight-bold">
                <i class="la la-eye"></i>
                Preview
              </button>
              &nbsp;
              <button
                v-on:click="reset($event)"
                class="btn btn-clean font-weight-bold"
              >
                <i class="la la-recycle"></i>
                Reset
              </button>
            </div>
          </div>
        </div>
      </form>
      <!--end::Form-->
    </div>

    <div class="card card-custom gutter-b">
      <div class="card-header">
        <div class="card-title">
          <h3 class="card-label">Generated Config</h3>
        </div>
      </div>
      <div class="card-body">
        <!--begin::Example-->
        <div class="example mb-10">
          <p>
            Use for layout config in
            <code>/src/core/config/layout.config.json</code>
          </p>
          <div class="example-code">
            <div class="example-code">
              <span
                class="example-copy"
                v-b-tooltip.hover.top="'Copy code'"
              ></span>
              <div class="example-highlight">
                <highlight-code lang="json" class="language-json">
                  {{ config }}
                </highlight-code>
              </div>
            </div>
          </div>
        </div>
        <!--end::Example-->
      </div>
    </div>
  </div>
</template>

<script>
import { mapGetters } from "vuex";
import { SET_BREADCRUMB } from "@/core/services/store/breadcrumbs.module";

export default {
  name: "builder",
  components: {},
  data() {
    return {
      tabIndex: 0
    };
  },
  computed: {
    ...mapGetters(["layoutConfig"]),

    config() {
      return this.layoutConfig();
    }
  },
  mounted() {
    // set the tab from previous
    this.setActivePreviousTab();

    this.$store.dispatch(SET_BREADCRUMB, [{ title: "Layout Builder" }]);

    this.$nextTick(() => {
      const hljs = this.$el.querySelectorAll(".hljs");
      hljs.forEach(hl => {
        hl.classList.remove("hljs");
        hl.classList.add(`language-${hl.classList[1]}`);
      });
    });
  },
  destroyed() {
    localStorage.removeItem("builderTab");
  },
  methods: {
    /**
     * Reset config
     */
    reset(event) {
      event.preventDefault();
      // remove existing saved config
      localStorage.removeItem("config");
      window.location.reload();
    },

    /**
     * Set previous tab active
     */
    setActivePreviousTab() {
      this.tabIndex = parseInt(localStorage.getItem("builderTab")) || 0;
      const links = this.$refs["builder-tab"].querySelectorAll(".nav-link");
      // remove active tab links
      for (let i = 0; i < links.length; i++) {
        links[i].classList.remove("active");
      }
      this.$refs["builder-tab"]
        .querySelector(`[data-tab="${this.tabIndex}"]`)
        .classList.add("active");
    },
    /**
     * Set current active on click
     * @param event
     */
    setActiveTab(event) {
      const tab = event.target.closest('[role="tablist"]');
      const links = tab.querySelectorAll(".nav-link");
      // remove active tab links
      for (let i = 0; i < links.length; i++) {
        links[i].classList.remove("active");
      }

      // set clicked tab index to bootstrap tab
      this.tabIndex = parseInt(event.target.getAttribute("data-tab"));

      // set current active tab
      event.target.classList.add("active");

      // keep active tab
      localStorage.setItem("builderTab", this.tabIndex);
    },

    /**
     * Submit form
     * @param event
     */
    submit(event) {
      event.preventDefault();
      // save new config to localStorage
      localStorage.setItem("config", JSON.stringify(this.config));
      window.location.reload();
    }
  }
};
</script>

// theme/angular/demo3/src/app/pages/builder/builder.component.ts
import {
  Component,
  OnInit,
  AfterViewInit,
  ViewChild,
  ElementRef,
} from '@angular/core';
import { NgForm } from '@angular/forms';
import { LayoutService } from '../../_metronic/core/';
import KTLayoutExamples from '../../../assets/js/layout/extended/examples';

@Component({
  selector: 'app-builder',
  templateUrl: './builder.component.html',
  styleUrls: ['./builder.component.scss'],
})
export class BuilderComponent implements OnInit, AfterViewInit {
  model: any;
  @ViewChild('form', { static: true }) form: NgForm;
  activeTabId = 1;
  constructor(private layout: LayoutService, private el: ElementRef) {}

  ngOnInit(): void {
    this.model = this.layout.getConfig();
  }

  setActiveTab(tabId: number) {
    this.activeTabId = tabId;
  }

  getActiveTabCSSClass(tabId: number) {
    if (tabId !== this.activeTabId) {
      return '';
    }

    return 'active';
  }

  resetPreview(): void {
    this.layout.refreshConfigToDefault();
  }

  submitPreview(): void {
    this.layout.setConfig(this.model);
    location.reload();
  }

  ngAfterViewInit() {
    // init code preview examples
    // see /src/assets/js/layout/extended/examples.js
    const elements = this.el.nativeElement.querySelectorAll('.example');
    KTLayoutExamples.init(elements);
  }
}

<app-notice [svg]="'./assets/media/svg/icons/Tools/Tools.svg'">
  <p>
    The layout builder is to assist your set and configure your preferred
    project layout specifications and preview it in real time. The configured
    layout options will be saved until you change or reset them. To use the
    layout builder, choose the layout options and click the
    <code>Preview</code> button to preview the changes.
  </p>
</app-notice>
<!--begin::Card-->
<div class="card card-custom gutter-b">
  <!--begin::Header-->
  <div class="card-header card-header-tabs-line">
    <ul class="nav nav-dark nav-bold nav-tabs nav-tabs-line" role="tablist">
      <li class="nav-item">
        <a
          (click)="setActiveTab(1)"
          class="nav-link cursor-pointer"
          [ngClass]="getActiveTabCSSClass(1)"
          role="tab"
        >
          Mobile Header
        </a>
      </li>
      <li class="nav-item">
        <a
          (click)="setActiveTab(2)"
          class="nav-link cursor-pointer"
          [ngClass]="getActiveTabCSSClass(2)"
          role="tab"
        >
          Subheader
        </a>
      </li>
      <li class="nav-item">
        <a
          (click)="setActiveTab(3)"
          class="nav-link cursor-pointer"
          [ngClass]="getActiveTabCSSClass(3)"
          role="tab"
        >
          Content
        </a>
      </li>
      <li class="nav-item">
        <a
          (click)="setActiveTab(4)"
          class="nav-link cursor-pointer"
          [ngClass]="getActiveTabCSSClass(4)"
          role="tab"
        >
          Aside
        </a>
      </li>
      <li class="nav-item">
        <a
          (click)="setActiveTab(5)"
          class="nav-link cursor-pointer"
          [ngClass]="getActiveTabCSSClass(5)"
          role="tab"
        >
          Footer
        </a>
      </li>
    </ul>
  </div>
  <!--end::Header-->
  <!--begin::Form-->
  <form class="form" novalidate #form="ngForm" (ngSubmit)="submitPreview()">
    <!--begin::Body-->
    <div class="card-body">
      <div class="tab-content pt-3">
        <!-- begin::Header -->
        <div class="tab-pane" [ngClass]="getActiveTabCSSClass(1)">
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Fixed Header:</label
            >
            <div class="col-lg-9 col-xl-4">
              <span class="switch switch-icon">
                <label>
                  <input
                    type="checkbox"
                    name="builder[header][self][fixed][mobile]"
                    [(ngModel)]="model.header.self.fixed.mobile"
                    value="true"
                  />
                  <span></span>
                </label>
              </span>
              <div class="form-text text-muted">
                Enable fixed header for mobile mode
              </div>
            </div>
          </div>
        </div>
        <!-- end::Header -->

        <!-- begin::Subheader -->
        <div class="tab-pane" [ngClass]="getActiveTabCSSClass(2)">
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Display Subheader:</label
            >
            <div class="col-lg-9 col-xl-4">
              <span class="switch switch-icon">
                <label>
                  <input
                    type="checkbox"
                    name="builder[subheader][display]"
                    [(ngModel)]="model.subheader.display"
                    value="true"
                  />
                  <span></span>
                </label>
              </span>
              <div class="form-text text-muted">Display subheader</div>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Fixed Subheader:</label
            >
            <div class="col-lg-9 col-xl-4">
              <span class="switch switch-icon">
                <label>
                  <input
                    type="checkbox"
                    name="builder[subheader][fixed]"
                    [(ngModel)]="model.subheader.fixed"
                    value="true"
                  />
                  <span></span>
                </label>
              </span>
              <div class="form-text text-muted">
                Enable fixed(sticky) subheader. Requires
                <code>Solid</code> subheader style.
              </div>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right">Width:</label>
            <div class="col-lg-9 col-xl-4">
              <select
                class="form-control form-control-solid"
                name="builder[subheader][width]"
                [(ngModel)]="model.subheader.width"
              >
                <option value="fluid">Fluid</option>
                <option value="fixed">Fixed</option>
              </select>
              <div class="form-text text-muted">Select layout width type.</div>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Subheader Style:</label
            >
            <div class="col-lg-9 col-xl-4">
              <select
                class="form-control form-control-solid"
                name="builder[subheader][style]"
                [(ngModel)]="model.subheader.style"
              >
                <option value="transparent">Transparent</option>
                <option value="solid">Solid</option>
              </select>
              <div class="form-text text-muted">Select subheader style</div>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Subheader Layout:</label
            >
            <div class="col-lg-9 col-xl-4">
              <select
                class="form-control form-control-solid"
                name="builder[layout][subheader][layoutVersion]"
                [(ngModel)]="model.subheader.layoutVersion"
              >
                <option value="v1">Subheader 1</option>
                <option value="v2">Subheader 2</option>
                <option value="v3">Subheader 3</option>
                <option value="v4">Subheader 4</option>
                <option value="v5">Subheader 5</option>
                <option value="v6">Subheader 6</option>
              </select>
              <div class="form-text text-muted">Select subheader layout</div>
            </div>
          </div>
        </div>
        <!-- end::Subheader -->

        <!-- begin::Content -->
        <div class="tab-pane" [ngClass]="getActiveTabCSSClass(3)">
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right">Width:</label>
            <div class="col-lg-9 col-xl-4">
              <select
                class="form-control form-control-solid"
                name="builder[content][width]"
                [(ngModel)]="model.content.width"
              >
                <option value="fluid">Fluid</option>
                <option value="fixed">Fixed</option>
              </select>
              <div class="form-text text-muted">Select layout width type.</div>
            </div>
          </div>
        </div>
        <!-- end::Content -->

        <!-- begin::Aside -->
        <div class="tab-pane" [ngClass]="getActiveTabCSSClass(4)">
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Display Secondary Panel:</label
            >
            <div class="col-lg-9 col-xl-6">
              <span class="switch switch-icon">
                <label>
                  <input
                    type="checkbox"
                    name="builder[aside][secondary][display]"
                    [(ngModel)]="model.aside.secondary.display"
                    value="true"
                  />
                  <span></span>
                </label>
              </span>
              <div class="form-text text-muted">
                Display aside secondary panel
              </div>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Minimize:</label
            >
            <div class="col-lg-9 col-xl-4">
              <span class="switch switch-icon">
                <label>
                  <input
                    type="checkbox"
                    name="builde[aside][self][minimize][toggle]"
                    [(ngModel)]="model.aside.self.minimize.toggle"
                    value="true"
                  />
                  <span></span>
                </label>
              </span>
              <div class="form-text text-muted">Allow aside minimizing</div>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Static aside menu:</label
            >
            <div class="col-lg-9 col-xl-6">
              <span class="switch switch-icon">
                <label>
                  <input
                    type="checkbox"
                    name="builder[aside][menu][static]"
                    [(ngModel)]="model.aside.menu.static"
                    value="true"
                  />
                  <span></span>
                </label>
              </span>
              <div class="form-text text-muted">Static aside menu</div>
            </div>
          </div>

          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Default Minimize:</label
            >
            <div class="col-lg-9 col-xl-4">
              <span class="switch switch-icon">
                <label>
                  <input
                    type="checkbox"
                    name="builder[aside][self][minimize][default]"
                    [(ngModel)]="model.aside.self.minimize.default"
                    value="true"
                  />
                  <span></span>
                </label>
              </span>
              <div class="form-text text-muted">
                Set aside minimized by default
              </div>
            </div>
          </div>
        </div>
        <!-- end::Aside -->

        <!-- begin::Footer -->
        <div class="tab-pane" [ngClass]="getActiveTabCSSClass(5)">
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right"
              >Fixed Desktop Footer:</label
            >
            <div class="col-lg-9 col-xl-4">
              <span class="switch switch-icon">
                <label>
                  <input
                    type="checkbox"
                    name="builder[footer][fixed]"
                    [(ngModel)]="model.footer.fixed"
                    value="true"
                  />
                  <span></span>
                </label>
              </span>
              <div class="form-text text-muted">Set fixed desktop footer</div>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-lg-3 col-form-label text-lg-right">Width:</label>
            <div class="col-lg-9 col-xl-4">
              <select
                class="form-control form-control-solid"
                name="builder[footer][width]"
                [(ngModel)]="model.footer.width"
              >
                <option value="fluid">Fluid</option>
                <option value="fixed">Fixed</option>
              </select>
              <div class="form-text text-muted">Select layout width type.</div>
            </div>
          </div>
        </div>
        <!-- end::Footer -->
      </div>
    </div>
    <!--end::Body-->
    <!--begin::Footer-->
    <div class="card-body">
      <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-8">
          <button type="submit" name="builder_submit" class="btn btn-primary">
            Preview
          </button>
          &nbsp;
          <button
            type="submit"
            (click)="resetPreview()"
            name="builder_reset"
            class="btn btn-secondary"
          >
            Reset
          </button>
        </div>
      </div>
    </div>
    <!--end::Footer-->
  </form>
  <!--end::Form-->
</div>
<!--end::Card-->

<div class="card card-custom gutter-b">
  <div class="card-header">
    <div class="card-title">
      <h3 class="card-label">Generated Config</h3>
    </div>
  </div>
  <div class="card-body">
    <!--begin::Example-->
    <div class="example mb-10">
      <p>
        Use for layout config in
        <code>/src/app/_metronic/configs/default-layout.config.ts</code>
      </p>
      <div class="example-code">
        <div class="example-code">
          <span
            class="example-copy"
            data-placement="left"
            ngbTooltip="Copy code"
          ></span>
          <div class="example-highlight">
            <pre><code [highlight]="model|json"></code></pre>
          </div>
        </div>
      </div>
    </div>
    <!--end::Example-->
  </div>
</div>
