// theme/react/demo2/src/_metronic/_partials/widgets/tiles/TilesWidget12.js
/* eslint-disable jsx-a11y/anchor-is-valid */
import React from "react";
import SVG from "react-inlinesvg";
import { toAbsoluteUrl } from "../../../_helpers";

export function TilesWidget12({
  className,
  iconColor = "success",
  widgetHeight = "150px",
}) {
  return (
    <>
      <div
        className={`card card-custom ${className}`}
        style={{ height: widgetHeight }}
      >
        <div className="card-body">
          <span className={`svg-icon svg-icon-3x svg-icon-${iconColor}`}>
            <SVG
              src={toAbsoluteUrl("/media/svg/icons/Communication/Group.svg")}
            />
          </span>
          <div className="text-dark font-weight-bolder font-size-h2 mt-3">
            8,600
          </div>

          <a
            href="#"
            className="text-muted text-hover-primary font-weight-bold font-size-lg mt-1"
          >
            New Customers
          </a>
        </div>
      </div>
    </>
  );
}

// theme/angular/demo3/src/app/_metronic/partials/content/widgets/tiles/tiles-widget12/tiles-widget12.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-tiles-widget12',
  templateUrl: './tiles-widget12.component.html',
})
export class TilesWidget12Component implements OnInit {
  @Input() cssClass = '';
  @Input() widgetHeight = '150px';
  @Input() iconColor = 'success';
  svgCSSClass;

  constructor() { }

  ngOnInit() {
    this.svgCSSClass = `svg-icon--${this.iconColor}`;
  }
}

<!--begin::Tiles Widget 12-->
<div
  class="card card-custom"
  [ngClass]="cssClass"
  [ngStyle]="{ height: widgetHeight }"
>
  <div class="card-body">
    <span
      [inlineSVG]="'./assets/media/svg/icons/Communication/Group.svg'"
      class="svg-icon svg-icon-3x"
      [ngClass]="svgCSSClass"
    ></span>
    <div class="text-dark font-weight-bolder font-size-h2 mt-3">8,600</div>
    <a
      href="#"
      class="text-muted text-hover-primary font-weight-bold font-size-lg mt-1"
      >New Customers</a
    >
  </div>
</div>
<!--end::Tiles Widget 12-->
