// angular/demo1/src/app/modules/wizards/steps/step5/step5.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-step5',
  templateUrl: './step5.component.html',
})
export class Step5Component {
  constructor() {}
}

<div class="pb-8 pb-lg-10">
  <h2 class="fw-bolder text-dark">Your Are Done!</h2>
  <div class="text-gray-400 fw-bold fs-6">
    If you need more info, please
    <a class="link-primary fw-bolder cursor-pointer"> Sign In</a>.
  </div>
</div>
<div class="mb-0">
  <div class="fs-6 text-gray-600 mb-5">
    Writing headlines for blog posts is as much an art as it is a science and
    probably warrants its own post, but for all advise is with what works for
    your great &amp; amazing audience.
  </div>
  <div
    class="
      notice
      d-flex
      bg-light-warning
      rounded
      border-warning border border-dashed
      p-6
    "
  >
    <span class="svg-icon svg-icon-2tx svg-icon-warning me-4"></span>
    <div class="d-flex flex-stack flex-grow-1">
      <div class="fw-bold">
        <h4 class="text-gray-800 fw-bolder">We need your attention!</h4>
        <div class="fs-6 text-gray-600">
          To start using great tools, please, please
          <a class="fw-bolder cursor-pointer"> Create Team Platform</a>
        </div>
      </div>
    </div>
  </div>
</div>

// react/demo1/src/app/modules/wizards/components/steps/Step5.tsx
import React, {FC} from 'react'
import {KTSVG} from '../../../../../_metronic/helpers'
import {Link} from 'react-router-dom'

const Step5: FC = () => {
  return (
    <div className='w-100'>
      <div className='pb-8 pb-lg-10'>
        <h2 className='fw-bolder text-dark'>Your Are Done!</h2>

        <div className='text-gray-400 fw-bold fs-6'>
          If you need more info, please
          <Link to='/auth/login' className='link-primary fw-bolder'>
            {' '}
            Sign In
          </Link>
          .
        </div>
      </div>

      <div className='mb-0'>
        <div className='fs-6 text-gray-600 mb-5'>
          Writing headlines for blog posts is as much an art as it is a science and probably
          warrants its own post, but for all advise is with what works for your great & amazing
          audience.
        </div>

        <div className='notice d-flex bg-light-warning rounded border-warning border border-dashed p-6'>
          <KTSVG
            path='/media/icons/duotune/general/gen044.svg'
            className='svg-icon-2tx svg-icon-warning me-4'
          />
          <div className='d-flex flex-stack flex-grow-1'>
            <div className='fw-bold'>
              <h4 className='text-gray-800 fw-bolder'>We need your attention!</h4>
              <div className='fs-6 text-gray-600'>
                To start using great tools, please, please
                <a href='/dashboard' className='fw-bolder'>
                  {' '}
                  Create Team Platform
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export {Step5}
