// react/demo2/src/app/modules/wizards/components/Vertical.tsx
import React, {FC, useEffect, useRef, useState} from 'react'
import {KTSVG} from '../../../../_metronic/helpers'
import {Step1} from './steps/Step1'
import {Step2} from './steps/Step2'
import {Step3} from './steps/Step3'
import {Step4} from './steps/Step4'
import {Step5} from './steps/Step5'
import {StepperComponent} from '../../../../_metronic/assets/ts/components'
import {Formik, Form, FormikValues} from 'formik'
import {ICreateAccount, createAccountSchemas, inits} from './CreateAccountWizardHelper'

const Vertical: FC = () => {
  const stepperRef = useRef<HTMLDivElement | null>(null)
  const stepper = useRef<StepperComponent | null>(null)
  const [currentSchema, setCurrentSchema] = useState(createAccountSchemas[0])
  const [initValues] = useState<ICreateAccount>(inits)

  const loadStepper = () => {
    stepper.current = StepperComponent.createInsance(stepperRef.current as HTMLDivElement)
  }

  const prevStep = () => {
    if (!stepper.current) {
      return
    }

    stepper.current.goPrev()

    setCurrentSchema(createAccountSchemas[stepper.current.currentStepIndex - 1])
  }

  const submitStep = (values: ICreateAccount, actions: FormikValues) => {
    if (!stepper.current) {
      return
    }

    setCurrentSchema(createAccountSchemas[stepper.current.currentStepIndex])

    if (stepper.current.currentStepIndex !== stepper.current.totatStepsNumber) {
      stepper.current.goNext()
    } else {
      stepper.current.goto(1)
      actions.resetForm()
    }
  }

  useEffect(() => {
    if (!stepperRef.current) {
      return
    }

    loadStepper()
  }, [stepperRef])

  return (
    <div
      ref={stepperRef}
      className='stepper stepper-pills stepper-column   d-flex flex-column flex-xl-row flex-row-fluid'
      id='kt_create_account_stepper'
    >
      <div className='d-flex justify-content-center bg-white rounded justify-content-xl-start flex-row-auto w-100 w-xl-300px w-xxl-400px me-9'>
        <div className='px-6 px-lg-10 px-xxl-15 py-20'>
          <div className='stepper-nav'>
            <div className='stepper-item current' data-kt-stepper-element='nav'>
              <div className='stepper-line w-40px'></div>

              <div className='stepper-icon w-40px h-40px'>
                <i className='stepper-check fas fa-check'></i>
                <span className='stepper-number'>1</span>
              </div>

              <div className='stepper-label'>
                <h3 className='stepper-title'>Account Type</h3>

                <div className='stepper-desc fw-bold'>Setup Your Account Details</div>
              </div>
            </div>

            <div className='stepper-item' data-kt-stepper-element='nav'>
              <div className='stepper-line w-40px'></div>

              <div className='stepper-icon w-40px h-40px'>
                <i className='stepper-check fas fa-check'></i>
                <span className='stepper-number'>2</span>
              </div>

              <div className='stepper-label'>
                <h3 className='stepper-title'>Account Settings</h3>
                <div className='stepper-desc fw-bold'>Setup Your Account Settings</div>
              </div>
            </div>

            <div className='stepper-item' data-kt-stepper-element='nav'>
              <div className='stepper-line w-40px'></div>

              <div className='stepper-icon w-40px h-40px'>
                <i className='stepper-check fas fa-check'></i>
                <span className='stepper-number'>3</span>
              </div>

              <div className='stepper-label'>
                <h3 className='stepper-title'>Business Info</h3>
                <div className='stepper-desc fw-bold'>Your Business Related Info</div>
              </div>
            </div>

            <div className='stepper-item' data-kt-stepper-element='nav'>
              <div className='stepper-line w-40px'></div>

              <div className='stepper-icon w-40px h-40px'>
                <i className='stepper-check fas fa-check'></i>
                <span className='stepper-number'>4</span>
              </div>

              <div className='stepper-label'>
                <h3 className='stepper-title'>Billing Details</h3>
                <div className='stepper-desc fw-bold'>Set Your Payment Methods</div>
              </div>
            </div>

            <div className='stepper-item' data-kt-stepper-element='nav'>
              <div className='stepper-line w-40px'></div>

              <div className='stepper-icon w-40px h-40px'>
                <i className='stepper-check fas fa-check'></i>
                <span className='stepper-number'>5</span>
              </div>

              <div className='stepper-label'>
                <h3 className='stepper-title'>Completed</h3>
                <div className='stepper-desc fw-bold'>Woah, we are here</div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className='d-flex flex-row-fluid flex-center bg-white rounded'>
        <Formik validationSchema={currentSchema} initialValues={initValues} onSubmit={submitStep}>
          {() => (
            <Form className='py-20 w-100 w-xl-700px px-9' noValidate id='kt_create_account_form'>
              <div className='current' data-kt-stepper-element='content'>
                <Step1 />
              </div>

              <div data-kt-stepper-element='content'>
                <Step2 />
              </div>

              <div data-kt-stepper-element='content'>
                <Step3 />
              </div>

              <div data-kt-stepper-element='content'>
                <Step4 />
              </div>

              <div data-kt-stepper-element='content'>
                <Step5 />
              </div>

              <div className='d-flex flex-stack pt-10'>
                <div className='mr-2'>
                  <button
                    onClick={prevStep}
                    type='button'
                    className='btn btn-lg btn-light-primary me-3'
                    data-kt-stepper-action='previous'
                  >
                    <KTSVG
                      path='/media/icons/duotune/arrows/arr063.svg'
                      className='svg-icon-4 me-1'
                    />
                    Back
                  </button>
                </div>

                <div>
                  <button type='submit' className='btn btn-lg btn-primary me-3'>
                    <span className='indicator-label'>
                      {stepper.current?.currentStepIndex !==
                        stepper.current?.totatStepsNumber! - 1 && 'Continue'}
                      {stepper.current?.currentStepIndex ===
                        stepper.current?.totatStepsNumber! - 1 && 'Submit'}
                      <KTSVG
                        path='/media/icons/duotune/arrows/arr064.svg'
                        className='svg-icon-3 ms-2 me-0'
                      />
                    </span>
                  </button>
                </div>
              </div>
            </Form>
          )}
        </Formik>
      </div>
    </div>
  )
}

export {Vertical}

// angular/demo1/src/app/modules/wizards/vertical/vertical.component.ts
import { Component, OnInit } from '@angular/core';
import { BehaviorSubject, Subscription } from 'rxjs';
import { ICreateAccount, inits } from '../create-account.helper';

@Component({
  selector: 'app-vertical',
  templateUrl: './vertical.component.html',
})
export class VerticalComponent implements OnInit {
  formsCount = 5;
  account$: BehaviorSubject<ICreateAccount> =
    new BehaviorSubject<ICreateAccount>(inits);
  currentStep$: BehaviorSubject<number> = new BehaviorSubject(1);
  isCurrentFormValid$: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(
    false
  );
  private unsubscribe: Subscription[] = [];

  constructor() {}

  ngOnInit(): void {}

  updateAccount = (part: Partial<ICreateAccount>, isFormValid: boolean) => {
    const currentAccount = this.account$.value;
    const updatedAccount = { ...currentAccount, ...part };
    this.account$.next(updatedAccount);
    this.isCurrentFormValid$.next(isFormValid);
  };

  nextStep() {
    const nextStep = this.currentStep$.value + 1;
    if (nextStep > this.formsCount) {
      return;
    }
    this.currentStep$.next(nextStep);
  }

  prevStep() {
    const prevStep = this.currentStep$.value - 1;
    if (prevStep === 0) {
      return;
    }
    this.currentStep$.next(prevStep);
  }

  ngOnDestroy() {
    this.unsubscribe.forEach((sb) => sb.unsubscribe());
  }
}

<div
  class="
    stepper stepper-pills stepper-column
    d-flex
    flex-column flex-xl-row flex-row-fluid
  "
  id="kt_create_account_stepper"
>
  <div
    class="
      d-flex
      justify-content-center
      bg-white
      rounded
      justify-content-xl-start
      flex-row-auto
      w-100 w-xl-300px w-xxl-400px
      me-9
    "
  >
    <div class="px-6 px-lg-10 px-xxl-15 py-20">
      <div class="stepper-nav">
        <div
          class="stepper-item"
          [ngClass]="{
            current: currentStep$.value === 1,
            completed: currentStep$.value > 1
          }"
        >
          <div class="stepper-line w-40px"></div>

          <div class="stepper-icon w-40px h-40px">
            <i class="stepper-check fas fa-check"></i>
            <span class="stepper-number">1</span>
          </div>

          <div class="stepper-label">
            <h3 class="stepper-title">Account Type</h3>

            <div class="stepper-desc fw-bold">Setup Your Account Details</div>
          </div>
        </div>

        <div
          class="stepper-item"
          [ngClass]="{
            current: currentStep$.value === 2,
            completed: currentStep$.value > 2
          }"
        >
          <div class="stepper-line w-40px"></div>

          <div class="stepper-icon w-40px h-40px">
            <i class="stepper-check fas fa-check"></i>
            <span class="stepper-number">2</span>
          </div>

          <div class="stepper-label">
            <h3 class="stepper-title">Account Settings</h3>
            <div class="stepper-desc fw-bold">Setup Your Account Settings</div>
          </div>
        </div>

        <div
          class="stepper-item"
          [ngClass]="{
            current: currentStep$.value === 3,
            completed: currentStep$.value > 3
          }"
        >
          <div class="stepper-line w-40px"></div>

          <div class="stepper-icon w-40px h-40px">
            <i class="stepper-check fas fa-check"></i>
            <span class="stepper-number">3</span>
          </div>

          <div class="stepper-label">
            <h3 class="stepper-title">Business Info</h3>
            <div class="stepper-desc fw-bold">Your Business Related Info</div>
          </div>
        </div>

        <div
          class="stepper-item"
          [ngClass]="{
            current: currentStep$.value === 4,
            completed: currentStep$.value > 4
          }"
        >
          <div class="stepper-line w-40px"></div>

          <div class="stepper-icon w-40px h-40px">
            <i class="stepper-check fas fa-check"></i>
            <span class="stepper-number">4</span>
          </div>

          <div class="stepper-label">
            <h3 class="stepper-title">Billing Details</h3>
            <div class="stepper-desc fw-bold">Set Your Payment Methods</div>
          </div>
        </div>

        <div
          class="stepper-item"
          [ngClass]="{ current: currentStep$.value === 5 }"
        >
          <div class="stepper-line w-40px"></div>

          <div class="stepper-icon w-40px h-40px">
            <i class="stepper-check fas fa-check"></i>
            <span class="stepper-number">5</span>
          </div>

          <div class="stepper-label">
            <h3 class="stepper-title">Completed</h3>
            <div class="stepper-desc fw-bold">Woah, we are here</div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="d-flex flex-row-fluid flex-center bg-white rounded">
    <form
      class="py-20 w-100 w-xl-700px px-9"
      noValidate
      id="kt_create_account_form"
    >
      <div class="current">
        <ng-container *ngIf="currentStep$.value === 1">
          <app-step1
            class="w-100"
            [updateParentModel]="updateAccount"
            [defaultValues]="account$.value"
          ></app-step1>
        </ng-container>

        <ng-container *ngIf="currentStep$.value === 2">
          <app-step2
            class="w-100"
            [updateParentModel]="updateAccount"
            [defaultValues]="account$.value"
          ></app-step2>
        </ng-container>

        <ng-container *ngIf="currentStep$.value === 3">
          <app-step3
            class="w-100"
            [updateParentModel]="updateAccount"
            [defaultValues]="account$.value"
          ></app-step3>
        </ng-container>

        <ng-container *ngIf="currentStep$.value === 4">
          <app-step4
            class="w-100"
            [updateParentModel]="updateAccount"
            [defaultValues]="account$.value"
          ></app-step4>
        </ng-container>

        <ng-container *ngIf="currentStep$.value === 5">
          <app-step5 class="w-100"></app-step5>
        </ng-container>
      </div>

      <div class="d-flex flex-stack pt-10">
        <div class="mr-2">
          <ng-container *ngIf="currentStep$.value !== 1">
            <button
              type="button"
              class="btn btn-lg btn-light-primary me-3"
              (click)="prevStep()"
            >
              <span
                [inlineSVG]="'./assets/media/icons/duotune/arrows/arr063.svg'"
                class="svg-icon svg-icon-4 me-1"
              ></span>
              Back
            </button>
          </ng-container>
        </div>

        <ng-container *ngIf="currentStep$.value !== formsCount">
          <div>
            <button
              type="button"
              class="btn btn-lg btn-primary me-3"
              [disabled]="!isCurrentFormValid$.value"
              (click)="nextStep()"
            >
              <span class="indicator-label">
                <ng-container *ngIf="currentStep$.value < formsCount - 1">
                  Continue {{ " " }}
                  <span
                    [inlineSVG]="
                      './assets/media/icons/duotune/arrows/arr064.svg'
                    "
                    class="svg-icon svg-icon-3 ms-2 me-0"
                  ></span>
                </ng-container>
                <ng-container *ngIf="currentStep$.value === formsCount - 1">
                  Submit
                </ng-container>
              </span>
            </button>
          </div>
        </ng-container>
      </div>
    </form>
  </div>
</div>
