// react/demo2/src/app/modules/wizards/components/steps/Step1.tsx
/* eslint-disable jsx-a11y/anchor-is-valid */
import React, {FC} from 'react'
import {KTSVG} from '../../../../../_metronic/helpers'
import {Field, ErrorMessage} from 'formik'

const Step1: FC = () => {
  return (
    <div className='w-100'>
      <div className='pb-10 pb-lg-15'>
        <h2 className='fw-bolder d-flex align-items-center text-dark'>
          Choose Account Type
          <i
            className='fas fa-exclamation-circle ms-2 fs-7'
            data-bs-toggle='tooltip'
            title='Billing is issued based on your selected account type'
          ></i>
        </h2>

        <div className='text-gray-400 fw-bold fs-6'>
          If you need more info, please check out
          <a href='#' className='link-primary fw-bolder'>
            {' '}
            Help Page
          </a>
          .
        </div>
      </div>

      <div className='fv-row'>
        <div className='row'>
          <div className='col-lg-6'>
            <Field
              type='radio'
              className='btn-check'
              name='accountType'
              value='personal'
              id='kt_create_account_form_account_type_personal'
            />
            <label
              className='btn btn-outline btn-outline-dashed btn-outline-default p-7 d-flex align-items-center mb-10'
              htmlFor='kt_create_account_form_account_type_personal'
            >
              <KTSVG
                path='/media/icons/duotune/communication/com005.svg'
                className='svg-icon-3x me-5'
              />

              <span className='d-block fw-bold text-start'>
                <span className='text-dark fw-bolder d-block fs-4 mb-2'>Personal Account</span>
                <span className='text-gray-400 fw-bold fs-6'>
                  If you need more info, please check it out
                </span>
              </span>
            </label>
          </div>

          <div className='col-lg-6'>
            <Field
              type='radio'
              className='btn-check'
              name='accountType'
              value='corporate'
              id='kt_create_account_form_account_type_corporate'
            />
            <label
              className='btn btn-outline btn-outline-dashed btn-outline-default p-7 d-flex align-items-center'
              htmlFor='kt_create_account_form_account_type_corporate'
            >
              <KTSVG path='/media/icons/duotune/finance/fin006.svg' className='svg-icon-3x me-5' />

              <span className='d-block fw-bold text-start'>
                <span className='text-dark fw-bolder d-block fs-4 mb-2'>Corporate Account</span>
                <span className='text-gray-400 fw-bold fs-6'>
                  Create corporate account to mane users
                </span>
              </span>
            </label>
          </div>

          <div className='fv-plugins-message-container invalid-feedback'>
            <ErrorMessage name='accountType' />
          </div>
        </div>
      </div>
    </div>
  )
}

export {Step1}

// angular/demo1/src/app/modules/wizards/steps/step1/step1.component.ts
import { Component, Input, OnDestroy, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Subscription } from 'rxjs';
import { ICreateAccount } from '../../create-account.helper';

@Component({
  selector: 'app-step1',
  templateUrl: './step1.component.html',
})
export class Step1Component implements OnInit, OnDestroy {
  @Input('updateParentModel') updateParentModel: (
    part: Partial<ICreateAccount>,
    isFormValid: boolean
  ) => void;
  form: FormGroup;
  @Input() defaultValues: Partial<ICreateAccount>;
  private unsubscribe: Subscription[] = [];

  constructor(private fb: FormBuilder) {}

  ngOnInit() {
    this.initForm();
    this.updateParentModel({}, true);
  }

  initForm() {
    this.form = this.fb.group({
      accountType: [this.defaultValues.accountType, [Validators.required]],
    });

    const formChangesSubscr = this.form.valueChanges.subscribe((val) => {
      this.updateParentModel(val, true);
    });
    this.unsubscribe.push(formChangesSubscr);
  }

  ngOnDestroy() {
    this.unsubscribe.forEach((sb) => sb.unsubscribe());
  }
}

<div class="pb-10 pb-lg-15">
  <h2 class="fw-bolder d-flex align-items-center text-dark">
    Choose Account Type
    <i
      class="fas fa-exclamation-circle ms-2 fs-7"
      ngbTooltip="Billing is issued based on your selected account type"
    ></i>
  </h2>

  <div class="text-gray-400 fw-bold fs-6">
    If you need more info, please check out
    <a href="#" class="link-primary fw-bolder"> Help Page </a>
    .
  </div>
</div>

<div class="fv-row" [formGroup]="form">
  <div class="row">
    <div class="col-lg-6">
      <input
        formControlName="accountType"
        name="accountType"
        type="radio"
        class="btn-check"
        id="kt_create_account_form_account_type_personal"
        value="personal"
      />
      <label
        class="
          btn btn-outline btn-outline-dashed btn-outline-default
          p-7
          d-flex
          align-items-center
          mb-10
        "
        for="kt_create_account_form_account_type_personal"
      >
        <span
          [inlineSVG]="'./assets/media/icons/duotune/communication/com005.svg'"
          class="svg-icon svg-icon-3x me-5"
        ></span>
        <span class="d-block fw-bold text-start">
          <span class="text-dark fw-bolder d-block fs-4 mb-2"
            >Personal Account</span
          >
          <span class="text-gray-400 fw-bold fs-6">
            If you need more info, please check it out
          </span>
        </span>
      </label>
    </div>

    <div class="col-lg-6">
      <input
        formControlName="accountType"
        name="accountType"
        type="radio"
        class="btn-check"
        id="kt_create_account_form_account_type_corporate"
        value="corporate"
      />
      <label
        class="
          btn btn-outline btn-outline-dashed btn-outline-default
          p-7
          d-flex
          align-items-center
        "
        for="kt_create_account_form_account_type_corporate"
      >
        <span
          [inlineSVG]="'./assets/media/icons/duotune/finance/fin006.svg'"
          class="svg-icon svg-icon-3x me-5"
        ></span>

        <span class="d-block fw-bold text-start">
          <span class="text-dark fw-bolder d-block fs-4 mb-2"
            >Corporate Account</span
          >
          <span class="text-gray-400 fw-bold fs-6">
            Create corporate account to mane users
          </span>
        </span>
      </label>
    </div>

    <div class="fv-plugins-message-container invalid-feedback">
      <!-- <ErrorMessage name='accountType' /> -->
    </div>
  </div>
</div>
