// angular/demo1/src/app/_metronic/partials/content/widgets/tiles/tiles-widget14/tiles-widget14.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-tiles-widget14',
  templateUrl: './tiles-widget14.component.html',
})
export class TilesWidget14Component {
  @Input() cssClass = '';
  constructor() {}
}

<!--begin::Mixed Widget 14-->
<div
  class="card card-custom bgi-no-repeat bgi-size-cover"
  [ngClass]="cssClass"
  style="background-image: url('./assets/media/stock-600x600/img-16.jpg')"
>
  <!--begin::Body-->
  <div
    class="card-body d-flex flex-column align-items-start justify-content-start"
  >
    <div class="p-1 flex-grow-1">
      <h3 class="text-white font-weight-bolder line-height-lg mb-5">
        Create Reports<br />With App
      </h3>
    </div>

    <a class="btn btn-link btn-link-warning font-weight-bold cursor-pointer">
      Create Report
      <span
        [inlineSVG]="'./assets/media/svg/icons/Navigation/Arrow-right.svg'"
        class="svg-icon ssvg-icon-lg svg-icon-warning"
      ></span>
    </a>
  </div>
  <!--end::Body-->
</div>
<!--end::Mixed Widget 14-->

// theme/react/demo1/src/_metronic/_partials/widgets/tiles/TilesWidget14.js
/* eslint-disable jsx-a11y/anchor-is-valid */
import React from "react";
import SVG from "react-inlinesvg";
import { toAbsoluteUrl } from "../../../_helpers";

export function TilesWidget14({ className }) {
  const backgroundImageUrl = toAbsoluteUrl("/media/stock-600x600/img-16.jpg");

  return (
    <>
      <div
        className={`card card-custom bgi-no-repeat bgi-size-cover ${className}`}
        style={{
          backgroundImage: `url("${backgroundImageUrl}")`,
        }}
      >
        {/* begin::Body */}
        <div className="card-body d-flex flex-column align-items-start justify-content-start">
          <div className="p-1 flex-grow-1">
            <h3 className="text-white font-weight-bolder line-height-lg mb-5">
              Create Reports
              <br />
              With App
            </h3>
          </div>

          <a
            href="#"
            className="btn btn-link btn-link-warning font-weight-bold"
          >
            Create Report
            <span className="svg-icon-lg svg-icon-warning">
              <SVG
                src={toAbsoluteUrl(
                  "/media/svg/icons/Navigation/Arrow-right.svg"
                )}
              />
            </span>
          </a>
        </div>
        {/* end::Body */}
      </div>
    </>
  );
}
