// theme/angular/demo2/src/app/_metronic/partials/content/widgets/tiles/tiles-widget11/tiles-widget11.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-tiles-widget11',
  templateUrl: './tiles-widget11.component.html',
})
export class TilesWidget11Component implements OnInit {
  @Input() cssClass = '';
  @Input() widgetHeight = '150px';
  @Input() baseColor = 'success';
  textInverseCSSClass;

  constructor() { }

  ngOnInit() {
    this.cssClass = `bg-${this.baseColor} ${this.cssClass}`;
    this.textInverseCSSClass = `text-inverse-${this.baseColor}`;
  }

}

<!--begin::Tiles Widget 11-->
<div
  class="card card-custom bg-"
  [ngClass]="cssClass"
  [ngStyle]="{ height: widgetHeight }"
>
  <div class="card-body">
    <span
      [inlineSVG]="'./assets/media/svg/icons/Layout/Layout-4-blocks.svg'"
      class="svg-icon svg-icon-3x svg-icon-white ml-n2"
    ></span>

    <div
      [ngClass]="textInverseCSSClass"
      class="font-weight-bolder font-size-h2 mt-3"
    >
      790
    </div>

    <a
      href="#"
      [ngClass]="textInverseCSSClass"
      class="font-weight-bold font-size-lg mt-1"
      >New Products</a
    >
  </div>
</div>
<!--end::Tiles Widget 11-->

// theme/react/demo1/src/_metronic/_partials/widgets/tiles/TilesWidget11.js
/* eslint-disable jsx-a11y/anchor-is-valid */
import React from "react";
import SVG from "react-inlinesvg";
import { toAbsoluteUrl } from "../../../_helpers";

export function TilesWidget11({
  className,
  baseColor = "primary",
  widgetHeight = "150px",
}) {
  return (
    <>
      <div
        className={`card card-custom bg-${baseColor} ${className}`}
        style={{ height: widgetHeight }}
      >
        <div className="card-body">
          <span className="svg-icon svg-icon-3x svg-icon-white ml-n2">
            <SVG src={toAbsoluteUrl("/media/svg/icons/Layout/Layout-4-blocks.svg")} />
          </span>
          <div
            className={`text-inverse-${baseColor} font-weight-bolder font-size-h2 mt-3`}
          >
            790
          </div>

          <a
            href="#"
            className={`text-inverse-${baseColor} font-weight-bold font-size-lg mt-1`}
          >
            New Products
          </a>
        </div>
      </div>
    </>
  );
}
