// theme/angular/demo1/src/app/_metronic/partials/content/widgets/tiles/tiles-widget13/tiles-widget13.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-tiles-widget13',
  templateUrl: './tiles-widget13.component.html',
})
export class TilesWidget13Component {
  @Input() cssClass = '';
  @Input() widgetHeight = '225px';

  constructor() { }
}

<!--begin::Tiles Widget 13-->
<div
  class="card card-custom bgi-no-repeat"
  [ngClass]="cssClass"
  [ngStyle]="{ height: widgetHeight }"
  style="
    background-color: #663259;
    background-position: calc(100% + 0.5rem) 100%;
    background-size: 100% auto;
    background-image: url('./assets/media/svg/patterns/taieri.svg');
  "
>
  <!--begin::Body-->
  <div class="card-body d-flex align-items-center">
    <div>
      <h3 class="text-white font-weight-bolder line-height-lg mb-5">
        Create SaaS<br />Based Reports
      </h3>
      <a href="#" class="btn btn-success font-weight-bold px-6 py-3"
        >Create Report</a
      >
    </div>
  </div>
  <!--end::Body-->
</div>
<!--end::Tiles Widget 13-->

// theme/react/demo1/src/_metronic/_partials/widgets/tiles/TilesWidget13.js
/* eslint-disable jsx-a11y/anchor-is-valid */
import React from "react";
import { toAbsoluteUrl } from "../../../_helpers";

export function TilesWidget13({ className, widgetHeight = "175px" }) {
  const backgroundImageUrl = toAbsoluteUrl("/media/svg/patterns/taieri.svg");

  return (
    <>
      <div
        className={`card card-custom bgi-no-repeat ${className}`}
        style={{ height: widgetHeight, backgroundColor: "#663259", backgroundPosition: "calc(100% + 0.5rem) 100%", backgroundSize: "100% auto", backgroundImage: `url("${backgroundImageUrl}")`  }}
      >
        {/* begin::Body */}
        <div className="card-body d-flex align-items-center">
        <div>
            <h3 className="text-white font-weight-bolder line-height-lg mb-5">Create SaaS<br/>Based Reports</h3>
            <a href='#' className="btn btn-success font-weight-bold px-6 py-3">Create Report</a>
        </div>
    </div>
        {/* end::Body */}
      </div>
    </>
  );
}
