// theme/react/demo2/src/_metronic/_partials/widgets/tiles/TilesWidget3.js
/* eslint-disable jsx-a11y/anchor-is-valid */
import React from "react";
import { toAbsoluteUrl } from "../../../_helpers";

export function TilesWidget3({ className, widgetHeight = "175px" }) {
  const backgroundImageUrl = toAbsoluteUrl("/media/bg/bg-9.jpg");
  return (
    <>
      {/* begin::Tiles Widget 3 */}
      <div
        className={`card card-custom bgi-no-repeat bgi-no-repeat bgi-size-cover ${className}`}
        style={{
          height: widgetHeight,
          backgroundImage: `url("${backgroundImageUrl}")`,
        }}
      >
        {/* begin::Body */}
        <div className="card-body d-flex flex-column">
          {/* begin::Title */}
          <a
            href="#"
            className="text-dark-75 text-hover-primary font-weight-bolder font-size-h3"
          >
            Properties
          </a>
          {/* end::Title */}
        </div>
        {/* end::Body */}
      </div>
      {/* end::Tiles Widget 3 */}
    </>
  );
}

// angular/demo1/src/app/_metronic/partials/content/widgets/tiles/tiles-widget3/tiles-widget3.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-tiles-widget3',
  templateUrl: './tiles-widget3.component.html',
})
export class TilesWidget3Component {
  @Input() cssClass = '';
  @Input() widgetHeight = '130px';

  constructor() {}
}

<!--begin::Tiles Widget 3-->
<div
  class="card card-custom bgi-no-repeat bgi-no-repeat bgi-size-cover"
  [ngClass]="cssClass"
  [ngStyle]="{ height: widgetHeight }"
  style="background-image: url('./assets/media/bg/bg-9.jpg')"
>
  <!--begin::Body-->
  <div class="card-body d-flex flex-column">
    <!--begin::Title-->
    <a
      class="
        text-dark-75 text-hover-primary
        font-weight-bolder font-size-h3
        cursor-pointer
      "
      >Properties</a
    >
    <!--end::Title-->
  </div>
  <!--end::Body-->
</div>
<!--end::Tiles Widget 3-->
