// vue/docs/src/views/documentation/get-started/DarkMode.vue
<template>
  <!--begin::Card-->
  <div class="card">
    <!--begin::Card Body-->
    <div class="card-body p-10 p-lg-15">
      <!--begin::Section-->
      <div class="pt-5">
        <!--begin::Heading-->
        <h1 class="anchor fw-bolder mb-5" id="quick_setup">
          <a href="#quick_setup"></a>
          Quick Setup
        </h1>
        <!--end::Heading-->

        <!--begin::Block-->
        <div class="pt-4">
          Metronic 8 demo1 and demo2 supports full <b>Dark Mode</b> that you can
          easily setup following the below instructions.
        </div>
        <!--end::Block-->

        <ol class="pt-4">
          <li>
            In file <code>demo1/src/App.vue</code> replace main scss files to
            dark mode.
            <CodeHighlighter lang="scss">{{
              `
@import "assets/sass/plugins.dark";
@import "assets/sass/style.dark";
`
            }}</CodeHighlighter>
          </li>
          <li>
            In file <code>demo1/public/index.html</code> add dark-mode class
            name to the <code>&lt;body&gt;</code> tag.
            <CodeHighlighter lang="html">{{ htmlCode }}</CodeHighlighter>
          </li>
        </ol>
      </div>
      <!--end::Section-->
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, onMounted } from "vue";
import { setCurrentPageBreadcrumbs } from "@/core/helpers/breadcrumb";
import { themeName } from "@/core/helpers/documentation";
import CodeHighlighter from "@/components/highlighters/CodeHighlighter.vue";

export default defineComponent({
  name: "dark-mode",
  components: {
    CodeHighlighter,
  },
  setup() {
    onMounted(() => {
      setCurrentPageBreadcrumbs("Dark mode", ["Getting Started"]);
    });

    const htmlCode = `<body class="dark-mode">`;

    return {
      themeName,
      htmlCode,
    };
  },
});
</script>

// angular/docs/src/app/getting-started/dark-mode/dark-mode.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-dark-mode',
  templateUrl: './dark-mode.component.html',
  styleUrls: ['./dark-mode.component.scss']
})
export class DarkModeComponent implements OnInit {
  code1 = `/* You can add global styles to this file, and also import other style files */
//@import "./assets/sass/style";

// Replace above style with this SCSS file to enable dark mode styles
@import "./assets/sass/style.dark";
`;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="pb-10">
  <h1 class="anchor fw-bolder mb-5" id="deployment">
    <a href="#deployment"></a>Dark Mode
  </h1>
  <div class="py-5">
    <ol class="my-0 py-0">
      <li class="py-2">Open file <code>demo1/src/styles.scss</code></li>
      <li class="py-2">Comment out <code>@import "./assets/sass/style";</code></li>
      <li class="py-2">Uncomment line <code>@import "./assets/sass/style.dark";</code></li>
    </ol>
    <app-code-block language="sass" [code]="code1"></app-code-block>
  </div>
</div>
