// theme/react/demo2/src/_metronic/_partials/dropdowns/DropdownMenu2.js
/* eslint-disable no-script-url,jsx-a11y/anchor-is-valid */
import React from "react";

export function DropdownMenu2() {
    return <>
        {/*begin::Navigation*/}
        <ul className="navi navi-hover">
            <li className="navi-header pb-1">
                <span className="text-primary text-uppercase font-weight-bold font-size-sm">Add new:</span>
            </li>
            <li className="navi-item">
                <a href="#" className="navi-link">
                    <span className="navi-icon"><i className="flaticon2-shopping-cart-1"></i></span>
                    <span className="navi-text">Order</span>
                </a>
            </li>
            <li className="navi-item">
                <a href="#" className="navi-link">
                    <span className="navi-icon"><i className="flaticon2-calendar-8"></i></span>
                    <span className="navi-text">Event</span>
                </a>
            </li>
            <li className="navi-item">
                <a href="#" className="navi-link">
                    <span className="navi-icon"><i className="flaticon2-graph-1"></i></span>
                    <span className="navi-text">Report</span>
                </a>
            </li>
            <li className="navi-item">
                <a href="#" className="navi-link">
                    <span className="navi-icon"><i className="flaticon2-rocket-1"></i></span>
                    <span className="navi-text">Post</span>
                </a>
            </li>
            <li className="navi-item">
                <a href="#" className="navi-link">
                    <span className="navi-icon"><i className="flaticon2-writing"></i></span>
                    <span className="navi-text">File</span>
                </a>
            </li>
        </ul>
        {/*end::Navigation*/}
    </>
}

// theme/angular/demo2/src/app/_metronic/partials/content/dropdown-menus/dropdown-menu2/dropdown-menu2.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-dropdown-menu2',
  templateUrl: './dropdown-menu2.component.html',
})
export class DropdownMenu2Component implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<!--begin::Navigation-->
<ul class="navi navi-hover">
  <li class="navi-header pb-1">
    <span class="text-primary text-uppercase font-weight-bold font-size-sm"
      >Add new:</span
    >
  </li>
  <li class="navi-item">
    <a class="navi-link cursor-pointer">
      <span class="navi-icon"><i class="flaticon2-shopping-cart-1"></i></span>
      <span class="navi-text">Order</span>
    </a>
  </li>
  <li class="navi-item">
    <a class="navi-link cursor-pointer">
      <span class="navi-icon"><i class="flaticon2-calendar-8"></i></span>
      <span class="navi-text">Event</span>
    </a>
  </li>
  <li class="navi-item">
    <a class="navi-link cursor-pointer">
      <span class="navi-icon"><i class="flaticon2-graph-1"></i></span>
      <span class="navi-text">Report</span>
    </a>
  </li>
  <li class="navi-item">
    <a class="navi-link cursor-pointer">
      <span class="navi-icon"><i class="flaticon2-rocket-1"></i></span>
      <span class="navi-text">Post</span>
    </a>
  </li>
  <li class="navi-item">
    <a class="navi-link cursor-pointer">
      <span class="navi-icon"><i class="flaticon2-writing"></i></span>
      <span class="navi-text">File</span>
    </a>
  </li>
</ul>
<!--end::Navigation-->
