// react/demo2/src/app/modules/wizards/components/steps/Step2.tsx
/* eslint-disable jsx-a11y/anchor-is-valid */
import React, {FC} from 'react'
import {KTSVG} from '../../../../../_metronic/helpers'
import {Field, ErrorMessage} from 'formik'

const Step2: FC = () => {
  return (
    <div className='w-100'>
      <div className='pb-10 pb-lg-15'>
        <h2 className='fw-bolder text-dark'>Account Info</h2>

        <div className='text-gray-400 fw-bold fs-6'>
          If you need more info, please check out
          <a href='#' className='link-primary fw-bolder'>
            {' '}
            Help Page
          </a>
          .
        </div>
      </div>

      <div className='mb-10 fv-row'>
        <label className='d-flex align-items-center form-label mb-3'>
          Specify Team Size
          <i
            className='fas fa-exclamation-circle ms-2 fs-7'
            data-bs-toggle='tooltip'
            title='Provide your team size to help us setup your billing'
          ></i>
        </label>

        <div className='row mb-2' data-kt-buttons='true'>
          <div className='col'>
            <Field
              type='radio'
              className='btn-check'
              name='accountTeamSize'
              value='1-1'
              id='kt_account_team_size_select_1'
            />
            <label
              className='btn btn-outline btn-outline-dashed btn-outline-default w-100 p-4'
              htmlFor='kt_account_team_size_select_1'
            >
              <span className='fw-bolder fs-3'>1-1</span>
            </label>
          </div>

          <div className='col'>
            <Field
              type='radio'
              className='btn-check'
              name='accountTeamSize'
              value='2-10'
              id='kt_account_team_size_select_2'
            />
            <label
              className='btn btn-outline btn-outline-dashed btn-outline-default w-100 p-4'
              htmlFor='kt_account_team_size_select_2'
            >
              <span className='fw-bolder fs-3'>2-10</span>
            </label>
          </div>

          <div className='col'>
            <Field
              type='radio'
              className='btn-check'
              name='accountTeamSize'
              value='10-50'
              id='kt_account_team_size_select_3'
            />
            <label
              className='btn btn-outline btn-outline-dashed btn-outline-default w-100 p-4'
              htmlFor='kt_account_team_size_select_3'
            >
              <span className='fw-bolder fs-3'>10-50</span>
            </label>
          </div>

          <div className='col'>
            <Field
              type='radio'
              className='btn-check'
              name='accountTeamSize'
              value='50+'
              id='kt_account_team_size_select_4'
            />
            <label
              className='btn btn-outline btn-outline-dashed btn-outline-default w-100 p-4'
              htmlFor='kt_account_team_size_select_4'
            >
              <span className='fw-bolder fs-3'>50+</span>
            </label>
          </div>
        </div>

        <div className='form-text'>
          Customers will see this shortened version of your statement descriptor
        </div>
      </div>

      <div className='mb-10 fv-row'>
        <label className='form-label mb-3'>Team Account Name</label>

        <Field
          type='text'
          className='form-control form-control-lg form-control-solid'
          name='accountName'
          placeholder=''
        />
        <div className='fv-plugins-message-container invalid-feedback'>
          <ErrorMessage name='accountName' />
        </div>
      </div>

      <div className='mb-0 fv-row'>
        <label className='d-flex align-items-center form-label mb-5'>
          Select Account Plan
          <i
            className='fas fa-exclamation-circle ms-2 fs-7'
            data-bs-toggle='tooltip'
            title='Monthly billing will be based on your account plan'
          ></i>
        </label>

        <div className='mb-0'>
          <label className='d-flex flex-stack mb-5 cursor-pointer'>
            <span className='d-flex align-items-center me-2'>
              <span className='symbol symbol-50px me-6'>
                <span className='symbol-label'>
                  <KTSVG
                    path='/media/icons/duotune/finance/fin001.svg'
                    className='svg-icon-1 svg-icon-gray-600'
                  />
                </span>
              </span>

              <span className='d-flex flex-column'>
                <span className='fw-bolder text-gray-800 text-hover-primary fs-5'>
                  Company Account
                </span>
                <span className='fs-6 fw-bold text-gray-400'>
                  Use images to enhance your post flow
                </span>
              </span>
            </span>

            <span className='form-check form-check-custom form-check-solid'>
              <Field className='form-check-input' type='radio' name='accountPlan' value='1' />
            </span>
          </label>

          <label className='d-flex flex-stack mb-5 cursor-pointer'>
            <span className='d-flex align-items-center me-2'>
              <span className='symbol symbol-50px me-6'>
                <span className='symbol-label'>
                  <KTSVG
                    path='/media/icons/duotune/graphs/gra006.svg'
                    className='svg-icon-1 svg-icon-gray-600'
                  />
                </span>
              </span>

              <span className='d-flex flex-column'>
                <span className='fw-bolder text-gray-800 text-hover-primary fs-5'>
                  Developer Account
                </span>
                <span className='fs-6 fw-bold text-gray-400'>Use images to your post time</span>
              </span>
            </span>

            <span className='form-check form-check-custom form-check-solid'>
              <Field className='form-check-input' type='radio' name='accountPlan' value='2' />
            </span>
          </label>

          <label className='d-flex flex-stack mb-0 cursor-pointer'>
            <span className='d-flex align-items-center me-2'>
              <span className='symbol symbol-50px me-6'>
                <span className='symbol-label'>
                  <KTSVG
                    path='/media/icons/duotune/graphs/gra008.svg'
                    className='svg-icon-1 svg-icon-gray-600'
                  />
                </span>
              </span>

              <span className='d-flex flex-column'>
                <span className='fw-bolder text-gray-800 text-hover-primary fs-5'>
                  Testing Account
                </span>
                <span className='fs-6 fw-bold text-gray-400'>
                  Use images to enhance time travel rivers
                </span>
              </span>
            </span>

            <span className='form-check form-check-custom form-check-solid'>
              <Field className='form-check-input' type='radio' name='accountPlan' value='3' />
            </span>
          </label>
        </div>
      </div>
    </div>
  )
}

export {Step2}

// angular/demo1/src/app/modules/wizards/steps/step2/step2.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Subscription } from 'rxjs';
import { ICreateAccount } from '../../create-account.helper';

@Component({
  selector: 'app-step2',
  templateUrl: './step2.component.html',
})
export class Step2Component implements OnInit {
  @Input('updateParentModel') updateParentModel: (
    part: Partial<ICreateAccount>,
    isFormValid: boolean
  ) => void;
  form: FormGroup;
  @Input() defaultValues: Partial<ICreateAccount>;

  private unsubscribe: Subscription[] = [];

  constructor(private fb: FormBuilder) {}

  ngOnInit() {
    this.initForm();
    this.updateParentModel({}, this.checkForm());
  }

  initForm() {
    this.form = this.fb.group({
      accountTeamSize: [
        this.defaultValues.accountTeamSize,
        [Validators.required],
      ],
      accountName: [this.defaultValues.accountName, [Validators.required]],
      accountPlan: [this.defaultValues.accountPlan, [Validators.required]],
    });

    const formChangesSubscr = this.form.valueChanges.subscribe((val) => {
      this.updateParentModel(val, this.checkForm());
    });
    this.unsubscribe.push(formChangesSubscr);
  }

  checkForm() {
    return !this.form.get('accountName')?.hasError('required');
  }

  ngOnDestroy() {
    this.unsubscribe.forEach((sb) => sb.unsubscribe());
  }
}

<div class="pb-10 pb-lg-15">
  <h2 class="fw-bolder text-dark">Account Info</h2>
  <div class="text-gray-400 fw-bold fs-6">
    If you need more info, please check out
    <a href="#" class="link-primary fw-bolder"> Help Page</a>.
  </div>
</div>
<div [formGroup]="form">
  <div class="mb-10 fv-row">
    <label class="d-flex align-items-center form-label mb-3"
      >Specify Team Size<i
        class="fas fa-exclamation-circle ms-2 fs-7"
        ngbTooltip="Provide your team size to help us setup your billing"
      ></i
    ></label>
    <div class="row mb-2" data-kt-buttons="true">
      <div class="col">
        <input
          formControlName="accountTeamSize"
          type="radio"
          class="btn-check"
          id="kt_account_team_size_select_1"
          value="1-1"
        /><label
          class="
            btn btn-outline btn-outline-dashed btn-outline-default
            w-100
            p-4
          "
          for="kt_account_team_size_select_1"
          ><span class="fw-bolder fs-3">1-1</span></label
        >
      </div>
      <div class="col">
        <input
          formControlName="accountTeamSize"
          type="radio"
          class="btn-check"
          id="kt_account_team_size_select_2"
          value="2-10"
        /><label
          class="
            btn btn-outline btn-outline-dashed btn-outline-default
            w-100
            p-4
          "
          for="kt_account_team_size_select_2"
          ><span class="fw-bolder fs-3">2-10</span></label
        >
      </div>
      <div class="col">
        <input
          formControlName="accountTeamSize"
          type="radio"
          class="btn-check"
          id="kt_account_team_size_select_3"
          value="10-50"
        /><label
          class="
            btn btn-outline btn-outline-dashed btn-outline-default
            w-100
            p-4
          "
          for="kt_account_team_size_select_3"
          ><span class="fw-bolder fs-3">10-50</span></label
        >
      </div>
      <div class="col">
        <input
          formControlName="accountTeamSize"
          type="radio"
          class="btn-check"
          id="kt_account_team_size_select_4"
          value="50+"
        /><label
          class="
            btn btn-outline btn-outline-dashed btn-outline-default
            w-100
            p-4
          "
          for="kt_account_team_size_select_4"
          ><span class="fw-bolder fs-3">50+</span></label
        >
      </div>
    </div>
    <div class="form-text">
      Customers will see this shortened version of your statement descriptor
    </div>
  </div>
  <div class="mb-10 fv-row">
    <label class="form-label mb-3 required">Team Account Name</label
    ><input
      formControlName="accountName"
      type="text"
      class="form-control form-control-lg form-control-solid"
      placeholder="Team Account name"
    />
    <div
      *ngIf="
        form.get('accountName')?.hasError('required') &&
        form.get('accountName')?.touched
      "
      class="fv-plugins-message-container invalid-feedback"
    >
      Team Account name is required
    </div>
  </div>
  <div class="mb-0 fv-row">
    <label class="d-flex align-items-center form-label mb-5"
      >Select Account Plan<i
        class="fas fa-exclamation-circle ms-2 fs-7"
        ngbTooltip="Monthly billing will be based on your account plan"
      ></i
    ></label>
    <div class="mb-0">
      <label class="d-flex flex-stack mb-5 cursor-pointer"
        ><span class="d-flex align-items-center me-2"
          ><span class="symbol symbol-50px me-6"
            ><span class="symbol-label"
              ><span
                [inlineSVG]="'./assets/media/icons/duotune/finance/fin001.svg'"
                class="svg-icon svg-icon-1 svg-icon-gray-600"
              ></span> </span></span
          ><span class="d-flex flex-column"
            ><span class="fw-bolder text-gray-800 text-hover-primary fs-5"
              >Company Account</span
            ><span class="fs-6 fw-bold text-gray-400"
              >Use images to enhance your post flow</span
            ></span
          ></span
        ><span class="form-check form-check-custom form-check-solid"
          ><input
            formControlName="accountPlan"
            class="form-check-input"
            type="radio"
            value="1" /></span></label
      ><label class="d-flex flex-stack mb-5 cursor-pointer"
        ><span class="d-flex align-items-center me-2"
          ><span class="symbol symbol-50px me-6"
            ><span class="symbol-label"
              ><span
                class="svg-icon svg-icon-1 svg-icon-gray-600"
                [inlineSVG]="'./assets/media/icons/duotune/graphs/gra006.svg'"
              ></span> </span></span
          ><span class="d-flex flex-column"
            ><span class="fw-bolder text-gray-800 text-hover-primary fs-5"
              >Developer Account</span
            ><span class="fs-6 fw-bold text-gray-400"
              >Use images to your post time</span
            ></span
          ></span
        ><span class="form-check form-check-custom form-check-solid"
          ><input
            formControlName="accountPlan"
            class="form-check-input"
            type="radio"
            value="2" /></span></label
      ><label class="d-flex flex-stack mb-0 cursor-pointer"
        ><span class="d-flex align-items-center me-2"
          ><span class="symbol symbol-50px me-6"
            ><span class="symbol-label"
              ><span
                class="svg-icon svg-icon-1 svg-icon-gray-600"
                [inlineSVG]="'./assets/media/icons/duotune/graphs/gra008.svg'"
              ></span> </span></span
          ><span class="d-flex flex-column"
            ><span class="fw-bolder text-gray-800 text-hover-primary fs-5"
              >Testing Account</span
            ><span class="fs-6 fw-bold text-gray-400"
              >Use images to enhance time travel rivers</span
            ></span
          ></span
        ><span class="form-check form-check-custom form-check-solid"
          ><input
            formControlName="accountPlan"
            class="form-check-input"
            type="radio"
            value="3" /></span
      ></label>
    </div>
  </div>
</div>
