// angular/demo1/src/app/modules/wizards/steps/step3/step3.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Subscription } from 'rxjs';
import { ICreateAccount } from '../../create-account.helper';

@Component({
  selector: 'app-step3',
  templateUrl: './step3.component.html',
})
export class Step3Component implements OnInit {
  @Input('updateParentModel') updateParentModel: (
    part: Partial<ICreateAccount>,
    isFormValid: boolean
  ) => void;
  form: FormGroup;
  @Input() defaultValues: Partial<ICreateAccount>;

  private unsubscribe: Subscription[] = [];

  constructor(private fb: FormBuilder) {}

  ngOnInit() {
    this.initForm();
    this.updateParentModel({}, this.checkForm());
  }

  initForm() {
    this.form = this.fb.group({
      businessName: [this.defaultValues.businessName, [Validators.required]],
      businessDescriptor: [
        this.defaultValues.businessDescriptor,
        [Validators.required],
      ],
      businessType: [this.defaultValues.businessType, [Validators.required]],
      businessDescription: [this.defaultValues.businessDescription],
      businessEmail: [
        this.defaultValues.businessEmail,
        [Validators.required, Validators.email],
      ],
    });

    const formChangesSubscr = this.form.valueChanges.subscribe((val) => {
      this.updateParentModel(val, this.checkForm());
    });
    this.unsubscribe.push(formChangesSubscr);
  }

  checkForm() {
    return !(
      this.form.get('businessName')?.hasError('required') ||
      this.form.get('businessDescriptor')?.hasError('required') ||
      this.form.get('businessType')?.hasError('required') ||
      this.form.get('businessEmail')?.hasError('required') ||
      this.form.get('businessEmail')?.hasError('email')
    );
  }

  ngOnDestroy() {
    this.unsubscribe.forEach((sb) => sb.unsubscribe());
  }
}

<div class="pb-10 pb-lg-12">
  <h2 class="fw-bolder text-dark">Business Details</h2>
  <div class="text-gray-400 fw-bold fs-6">
    If you need more info, please check out
    <a href="#" class="link-primary fw-bolder">Help Page</a>.
  </div>
</div>
<div [formGroup]="form">
  <div class="fv-row mb-10">
    <label class="form-label required">Business Name</label
    ><input
      name="businessName"
      class="form-control form-control-lg form-control-solid"
      formControlName="businessName"
    />
    <div
      class="fv-plugins-message-container invalid-feedback"
      *ngIf="
        form.get('businessName')?.hasError('required') &&
        form.get('businessName')?.touched
      "
    >
      Business Name is required
    </div>
  </div>
  <div class="fv-row mb-10">
    <label class="d-flex align-items-center form-label"
      ><span class="required">Shortened Descriptor</span></label
    ><input
      name="businessDescriptor"
      class="form-control form-control-lg form-control-solid"
      formControlName="businessDescriptor"
    />
    <div
      class="fv-plugins-message-container invalid-feedback"
      *ngIf="
        form.get('businessDescriptor')?.hasError('required') &&
        form.get('businessDescriptor')?.touched
      "
    >
      Shortened Descriptor is required
    </div>
    <div class="form-text">
      Customers will see this shortened version of your statement descriptor
    </div>
  </div>
  <div class="fv-row mb-10">
    <label class="form-label required">Corporation Type</label
    ><select
      name="businessType"
      class="form-select form-select-lg form-select-solid"
      formControlName="businessType"
    >
      <option value="1">S Corporation</option>
      <option value="1">C Corporation</option>
      <option value="2">Sole Proprietorship</option>
      <option value="3">Non-profit</option>
      <option value="4">Limited Liability</option>
      <option value="5">General Partnership</option>
    </select>
  </div>
  <div class="fv-row mb-10">
    <label class="form-label">Business Description</label
    ><textarea
      name="businessDescription"
      class="form-control form-control-lg form-control-solid"
      rows="3"
      formControlName="businessDescription"
    ></textarea>
  </div>
  <div class="fv-row mb-0">
    <label class="fs-6 fw-bold form-label required">Contact Email</label
    ><input
      name="businessEmail"
      class="form-control form-control-lg form-control-solid"
      formControlName="businessEmail"
    />
    <div
      class="fv-plugins-message-container invalid-feedback"
      *ngIf="
        form.get('businessEmail')?.hasError('required') &&
        form.get('businessEmail')?.touched
      "
    >
      Contact Email is required
    </div>
    <div
      class="fv-plugins-message-container invalid-feedback"
      *ngIf="
        form.get('businessEmail')?.hasError('email') &&
        form.get('businessEmail')?.touched
      "
    >
      Wrong email format
    </div>
  </div>
</div>

// react/demo2/src/app/modules/wizards/components/steps/Step3.tsx
/* eslint-disable jsx-a11y/anchor-is-valid */
import React, {FC} from 'react'
import {Field, ErrorMessage} from 'formik'

const Step3: FC = () => {
  return (
    <div className='w-100'>
      <div className='pb-10 pb-lg-12'>
        <h2 className='fw-bolder text-dark'>Business Details</h2>

        <div className='text-gray-400 fw-bold fs-6'>
          If you need more info, please check out
          <a href='#' className='link-primary fw-bolder'>
            Help Page
          </a>
          .
        </div>
      </div>

      <div className='fv-row mb-10'>
        <label className='form-label required'>Business Name</label>

        <Field name='businessName' className='form-control form-control-lg form-control-solid' />
        <div className='fv-plugins-message-container invalid-feedback'>
          <ErrorMessage name='businessName' />
        </div>
      </div>

      <div className='fv-row mb-10'>
        <label className='d-flex align-items-center form-label'>
          <span className='required'>Shortened Descriptor</span>
        </label>

        <Field
          name='businessDescriptor'
          className='form-control form-control-lg form-control-solid'
        />
        <div className='fv-plugins-message-container invalid-feedback'>
          <ErrorMessage name='businessDescriptor' />
        </div>

        <div className='form-text'>
          Customers will see this shortened version of your statement descriptor
        </div>
      </div>

      <div className='fv-row mb-10'>
        <label className='form-label required'>Corporation Type</label>

        <Field
          as='select'
          name='businessType'
          className='form-select form-select-lg form-select-solid'
        >
          <option></option>
          <option value='1'>S Corporation</option>
          <option value='1'>C Corporation</option>
          <option value='2'>Sole Proprietorship</option>
          <option value='3'>Non-profit</option>
          <option value='4'>Limited Liability</option>
          <option value='5'>General Partnership</option>
        </Field>
        <div className='fv-plugins-message-container invalid-feedback'>
          <ErrorMessage name='businessType' />
        </div>
      </div>

      <div className='fv-row mb-10'>
        <label className='form-label'>Business Description</label>

        <Field
          as='textarea'
          name='businessDescription'
          className='form-control form-control-lg form-control-solid'
          rows={3}
        ></Field>
      </div>

      <div className='fv-row mb-0'>
        <label className='fs-6 fw-bold form-label required'>Contact Email</label>

        <Field name='businessEmail' className='form-control form-control-lg form-control-solid' />
        <div className='fv-plugins-message-container invalid-feedback'>
          <ErrorMessage name='businessEmail' />
        </div>
      </div>
    </div>
  )
}

export {Step3}
