// react/docs/src/app/gettings-started/Changelog.tsx
import React from 'react'
import {KTSVG} from '../../_metronic/helpers'

export function Changelog() {
  const {REACT_APP_THEME_NAME, REACT_APP_VERSION} = process.env

  return (
    <>
      <div className='accordion accordion-flush accordion-icon-toggle' id='kt_accordion'>
        <div className='accordion-item mb-5'>
          <div
              className='accordion-header py-3 d-flex'
              data-bs-toggle='collapse'
              data-bs-target='#kt_accordion_body_v8_0_24'
              aria-expanded='true'
          >
            <span className='accordion-icon'>
              <KTSVG
                  path='/media/icons/duotune/arrows/arr064.svg'
                  className='svg-icon svg-icon-3'
              />
            </span>
            <h3 className='fs-3 text-gray-800 fw-bolder mb-0 ms-4'>
              {REACT_APP_THEME_NAME} {REACT_APP_VERSION} - September 20, 2021
            </h3>
          </div>
          <div
              id='kt_accordion_body_v8_0_24'
              className='fs-6 my-1 py-0 ps-10 collapse show'
              data-bs-parent='#kt_accordion'
          >
            <div className='accordion-body ps-0 pt-0'>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>Update:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>Updated Explore drawer. <a href="https://preview.keenthemes.com/metronic8/react/demo1">Preview</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div className='accordion-item mb-5'>
          <div
              className='accordion-header py-3 d-flex collapsed'
              data-bs-toggle='collapse'
              data-bs-target='#kt_accordion_body_v8_0_24'
              aria-expanded='true'
          >
            <span className='accordion-icon'>
              <KTSVG
                  path='/media/icons/duotune/arrows/arr064.svg'
                  className='svg-icon svg-icon-3'
              />
            </span>
            <h3 className='fs-3 text-gray-800 fw-bolder mb-0 ms-4'>
              {REACT_APP_THEME_NAME} v8.0.24 - September 2, 2021
            </h3>
          </div>
          <div
              id='kt_accordion_body_v8_0_24'
              className='fs-6 my-1 py-0 ps-10 collapse'
              data-bs-parent='#kt_accordion'
          >
            <div className='accordion-body ps-0 pt-0'>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>Update:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>SwapperComponent improvements.</li>
                </ul>
              </div>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>Fixes:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>
                    Fixed breadcrumbs on mobile version. <a href="https://preview.keenthemes.com/metronic8/react/demo1/dashboard">Preview</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div className='accordion-item mb-5'>
          <div
            className='accordion-header py-3 d-flex collapsed'
            data-bs-toggle='collapse'
            data-bs-target='#kt_accordion_body_v8_0_23'
            aria-expanded='true'
          >
            <span className='accordion-icon'>
              <KTSVG
                path='/media/icons/duotune/arrows/arr064.svg'
                className='svg-icon svg-icon-3'
              />
            </span>
            <h3 className='fs-3 text-gray-800 fw-bolder mb-0 ms-4'>
              {REACT_APP_THEME_NAME} v8.0.23 - August 20, 2021
            </h3>
          </div>
          <div
            id='kt_accordion_body_v8_0_23'
            className='fs-6 my-1 py-0 ps-10 collapse'
            data-bs-parent='#kt_accordion'
          >
            <div className='accordion-body ps-0 pt-0'>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>New:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>
                    RTL version setup doc.{' '}
                    <a href='https://preview.keenthemes.com/metronic8/react/demo1-docs/docs/rtl'>
                      Preview
                    </a>
                  </li>
                </ul>
              </div>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>Update:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>
                    Migration to new doutone icons set.{' '}
                    <a href='https://preview.keenthemes.com/metronic8/react/demo1-docs/docs/icons/duotune'>
                      Preview
                    </a>
                  </li>
                  <li className='py-2'>Migration to new illustrations set.</li>
                  <li className='py-2'>DrawerComponent improvements.</li>
                </ul>
              </div>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>Fixes:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>
                    Duplicated drawer overlay on second DrawerComponent initialization.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div className='accordion-item mb-5'>
          <div
            className='accordion-header py-3 d-flex collapsed'
            data-bs-toggle='collapse'
            data-bs-target='#kt_accordion_body_v8_0_22'
            aria-expanded='true'
          >
            <span className='accordion-icon'>
              <KTSVG
                path='/media/icons/duotune/arrows/arr064.svg'
                className='svg-icon svg-icon-3'
              />
            </span>
            <h3 className='fs-3 text-gray-800 fw-bolder mb-0 ms-4'>
              {REACT_APP_THEME_NAME} v8.0.22 - August 6, 2021
            </h3>
          </div>
          <div
            id='kt_accordion_body_v8_0_22'
            className='fs-6 my-1 py-0 ps-10 collapse'
            data-bs-parent='#kt_accordion'
          >
            <div className='accordion-body ps-0 pt-0'>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>New:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>
                    Added demo2 react version.{' '}
                    <a href='https://preview.keenthemes.com/metronic/react/demo1/dashboard'>
                      Preview
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div className='accordion-item mb-5'>
          <div
            className='accordion-header py-3 d-flex collapsed'
            data-bs-toggle='collapse'
            data-bs-target='#kt_accordion_body_v8_0_21'
            aria-expanded='true'
          >
            <span className='accordion-icon'>
              <KTSVG
                path='/media/icons/duotune/arrows/arr064.svg'
                className='svg-icon svg-icon-3'
              />
            </span>
            <h3 className='fs-3 text-gray-800 fw-bolder mb-0 ms-4'>
              {REACT_APP_THEME_NAME} v8.0.21 - July 30, 2021
            </h3>
          </div>
          <div
            id='kt_accordion_body_v8_0_21'
            className='fs-6 my-1 py-0 ps-10 collapse'
            data-bs-parent='#kt_accordion'
          >
            <div className='accordion-body ps-0 pt-0'>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>New:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>
                    Dark mode setup doc.{' '}
                    <a href='https://preview.keenthemes.com/metronic8/react/demo1-docs/docs/dark-mode'>
                      Preview
                    </a>
                  </li>
                </ul>
              </div>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>Fix:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>
                    <code className='ms-0'>Error page </code> redirect issue. Now we have page
                    refresh after redirect from Error pages.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div className='accordion-item mb-5'>
          <div
            className='accordion-header py-3 d-flex collapsed'
            data-bs-toggle='collapse'
            data-bs-target='#kt_accordion_body_v1_0_0'
            aria-expanded='true'
          >
            <span className='accordion-icon'>
              <KTSVG
                path='/media/icons/duotune/arrows/arr064.svg'
                className='svg-icon svg-icon-3'
              />
            </span>
            <h3 className='fs-3 text-gray-800 fw-bolder mb-0 ms-4'>
              {REACT_APP_THEME_NAME} v8.0.19 - July 20, 2021
            </h3>
          </div>
          <div
            id='kt_accordion_body_v1_0_0'
            className='fs-6 my-1 py-0 ps-10 collapse'
            data-bs-parent='#kt_accordion'
          >
            <div className='accordion-body ps-0 pt-0'>
              <ul className='my-0 py-0'>
                <li className='py-2'>Initial release</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

// angular/docs/src/app/getting-started/changelog/changelog.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-changelog',
  templateUrl: './changelog.component.html',
  styleUrls: ['./changelog.component.scss']
})
export class ChangelogComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="accordion accordion-flush accordion-icon-toggle" id="kt_accordion">
  <div class="accordion-item mb-5">
    <div
      class="accordion-header py-3 d-flex"
      data-bs-toggle="collapse"
      data-bs-target="#kt_accordion_body_v8_0_25"
      aria-expanded="true"
    >
      <span class="accordion-icon"
        ><span class="svg-icon svg-icon svg-icon-3"
          ><svg
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            class="mh-50px"
          >
            <rect
              opacity="0.5"
              x="18"
              y="13"
              width="13"
              height="2"
              rx="1"
              transform="rotate(-180 18 13)"
              fill="black"
            ></rect>
            <path
              d="M15.4343 12.5657L11.25 16.75C10.8358 17.1642 10.8358 17.8358 11.25 18.25C11.6642 18.6642 12.3358 18.6642 12.75 18.25L18.2929 12.7071C18.6834 12.3166 18.6834 11.6834 18.2929 11.2929L12.75 5.75C12.3358 5.33579 11.6642 5.33579 11.25 5.75C10.8358 6.16421 10.8358 6.83579 11.25 7.25L15.4343 11.4343C15.7467 11.7467 15.7467 12.2533 15.4343 12.5657Z"
              fill="black"
            ></path></svg></span
      ></span>
      <h3 class="fs-3 text-gray-800 fw-bolder mb-0 ms-4">
        Metronic v8.0.25 - September 20, 2021
      </h3>
    </div>
    <div
      id="kt_accordion_body_v8_0_25"
      class="fs-6 my-1 py-0 ps-10 collapse show"
      data-bs-parent="#kt_accordion"
    >
      <div class="accordion-body ps-0 pt-0">
        <div class="mb-5">
          <h4 class="fs-6 fw-bold mb-1">New:</h4>
          <ul class="my-0 py-0">
            <li class="py-2">Added new <code>dark mode</code> in demo1.</li>
          </ul>
        </div>
        <div class="mb-5">
          <h4 class="fs-6 fw-bold mb-1">Fix:</h4>
          <ul class="my-0 py-0">
            <li class="py-2">Fixed minimize aside icon.</li>
            <li class="py-2">Fixed <code>KTMenu</code> flip.</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="accordion-item mb-5">
    <div
      class="accordion-header py-3 d-flex"
      data-bs-toggle="collapse"
      data-bs-target="#kt_accordion_body_v8_0_24"
      aria-expanded="true"
    >
      <span class="accordion-icon"
        ><span class="svg-icon svg-icon svg-icon-3"
          ><svg
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            class="mh-50px"
          >
            <rect
              opacity="0.5"
              x="18"
              y="13"
              width="13"
              height="2"
              rx="1"
              transform="rotate(-180 18 13)"
              fill="black"
            ></rect>
            <path
              d="M15.4343 12.5657L11.25 16.75C10.8358 17.1642 10.8358 17.8358 11.25 18.25C11.6642 18.6642 12.3358 18.6642 12.75 18.25L18.2929 12.7071C18.6834 12.3166 18.6834 11.6834 18.2929 11.2929L12.75 5.75C12.3358 5.33579 11.6642 5.33579 11.25 5.75C10.8358 6.16421 10.8358 6.83579 11.25 7.25L15.4343 11.4343C15.7467 11.7467 15.7467 12.2533 15.4343 12.5657Z"
              fill="black"
            ></path></svg></span
      ></span>
      <h3 class="fs-3 text-gray-800 fw-bolder mb-0 ms-4">
        Metronic v8.0.24 - September 3, 2021
      </h3>
    </div>
    <div
      id="kt_accordion_body_v8_0_24"
      class="fs-6 my-1 py-0 ps-10 collapse show"
      data-bs-parent="#kt_accordion"
    >
      <div class="accordion-body ps-0 pt-0">
        <li class="py-2">Initial release</li>
      </div>
    </div>
  </div>
</div>
