// angular/demo1/src/app/modules/account/overview/overview.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-overview',
  templateUrl: './overview.component.html',
})
export class OverviewComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<div class="card mb-5 mb-xl-10" id="kt_profile_details_view">
  <div class="card-header cursor-pointer">
    <div class="card-title m-0">
      <h3 class="fw-bolder m-0">Profile Details</h3>
    </div>

    <a
      routerLink="/crafted/account/settings"
      class="btn btn-primary align-self-center"
    >
      Edit Profile
    </a>
  </div>

  <div class="card-body p-9">
    <div class="row mb-7">
      <label class="col-lg-4 fw-bold text-muted">Full Name</label>

      <div class="col-lg-8">
        <span class="fw-bolder fs-6 text-dark">Max Smith</span>
      </div>
    </div>

    <div class="row mb-7">
      <label class="col-lg-4 fw-bold text-muted">Company</label>

      <div class="col-lg-8 fv-row">
        <span class="fw-bold fs-6">Keenthemes</span>
      </div>
    </div>

    <div class="row mb-7">
      <label class="col-lg-4 fw-bold text-muted">
        Contact Phone
        <i
          class="fas fa-exclamation-circle ms-1 fs-7"
          data-bs-toggle="tooltip"
          title="Phone number must be active"
        ></i>
      </label>

      <div class="col-lg-8 d-flex align-items-center">
        <span class="fw-bolder fs-6 me-2">044 3276 454 935</span>

        <span class="badge badge-success">Verified</span>
      </div>
    </div>

    <div class="row mb-7">
      <label class="col-lg-4 fw-bold text-muted">Company Site</label>

      <div class="col-lg-8">
        <a href="#" class="fw-bold fs-6 text-dark text-hover-primary">
          keenthemes.com
        </a>
      </div>
    </div>

    <div class="row mb-7">
      <label class="col-lg-4 fw-bold text-muted">
        Country
        <i
          class="fas fa-exclamation-circle ms-1 fs-7"
          data-bs-toggle="tooltip"
          title="Country of origination"
        ></i>
      </label>

      <div class="col-lg-8">
        <span class="fw-bolder fs-6 text-dark">Germany</span>
      </div>
    </div>

    <div class="row mb-7">
      <label class="col-lg-4 fw-bold text-muted">Communication</label>

      <div class="col-lg-8">
        <span class="fw-bolder fs-6 text-dark">Email, Phone</span>
      </div>
    </div>

    <div class="row mb-10">
      <label class="col-lg-4 fw-bold text-muted">Allow Changes</label>

      <div class="col-lg-8">
        <span class="fw-bold fs-6">Yes</span>
      </div>
    </div>

    <div
      class="
        notice
        d-flex
        bg-light-warning
        rounded
        border-warning border border-dashed
        p-6
      "
    >
      <span
        [inlineSVG]="'./assets/media/icons/duotune/general/gen044.svg'"
        class="svg-icon svg-icon-2tx svg-icon-warning me-4"
      ></span>
      <div class="d-flex flex-stack flex-grow-1">
        <div class="fw-bold">
          <h4 class="text-gray-800 fw-bolder">We need your attention!</h4>
          <div class="fs-6 text-gray-600">
            Your payment was declined. To start using tools, please
            <a class="fw-bolder" routerLink="/crafted/account/settings">
              {{ " " }}
              Add Payment Method
            </a>
            .
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row gy-10 gx-xl-10">
  <div class="col-xl-6">
    <app-charts-widget1
      class="card card-xxl-stretch mb-5 mb-xl-10"
    ></app-charts-widget1>
  </div>

  <div class="col-xl-6">
    <app-tables-widget1
      class="card card-xxl-stretch mb-5 mb-xl-10"
    ></app-tables-widget1>
  </div>
</div>

<div class="row gy-10 gx-xl-10">
  <div class="col-xl-6">
    <app-lists-widget5
      class="card card-xxl-stretch mb-5 mb-xl-10"
    ></app-lists-widget5>
  </div>

  <div class="col-xl-6">
    <app-tables-widget5
      class="card card-xxl-stretch mb-5 mb-xl-10"
    ></app-tables-widget5>
  </div>
</div>

// vue/demo7/src/views/crafted/account/Overview.vue
<template>
  <!--begin::details View-->
  <div class="card mb-5 mb-xl-10" id="kt_profile_details_view">
    <!--begin::Card header-->
    <div class="card-header cursor-pointer">
      <!--begin::Card title-->
      <div class="card-title m-0">
        <h3 class="fw-bolder m-0">Profile Details</h3>
      </div>
      <!--end::Card title-->

      <!--begin::Action-->
      <router-link
        to="/account/settings"
        class="btn btn-primary align-self-center"
        >Edit Profile</router-link
      >
      <!--end::Action-->
    </div>
    <!--begin::Card header-->

    <!--begin::Card body-->
    <div class="card-body p-9">
      <!--begin::Row-->
      <div class="row mb-7">
        <!--begin::Label-->
        <label class="col-lg-4 fw-bold text-muted">Full Name</label>
        <!--end::Label-->

        <!--begin::Col-->
        <div class="col-lg-8">
          <span class="fw-bolder fs-6 text-dark">Max Smith</span>
        </div>
        <!--end::Col-->
      </div>
      <!--end::Row-->

      <!--begin::Input group-->
      <div class="row mb-7">
        <!--begin::Label-->
        <label class="col-lg-4 fw-bold text-muted">Company</label>
        <!--end::Label-->

        <!--begin::Col-->
        <div class="col-lg-8 fv-row">
          <span class="fw-bold fs-6">Keenthemes</span>
        </div>
        <!--end::Col-->
      </div>
      <!--end::Input group-->

      <!--begin::Input group-->
      <div class="row mb-7">
        <!--begin::Label-->
        <label class="col-lg-4 fw-bold text-muted">
          Contact Phone
          <i
            class="fas fa-exclamation-circle ms-1 fs-7"
            data-bs-toggle="tooltip"
            title="Phone number must be active"
          ></i>
        </label>
        <!--end::Label-->

        <!--begin::Col-->
        <div class="col-lg-8 d-flex align-items-center">
          <span class="fw-bolder fs-6 me-2">044 3276 454 935</span>

          <span class="badge badge-success">Verified</span>
        </div>
        <!--end::Col-->
      </div>
      <!--end::Input group-->

      <!--begin::Input group-->
      <div class="row mb-7">
        <!--begin::Label-->
        <label class="col-lg-4 fw-bold text-muted">Company Site</label>
        <!--end::Label-->

        <!--begin::Col-->
        <div class="col-lg-8">
          <a href="#" class="fw-bold fs-6 text-dark text-hover-primary"
            >keenthemes.com</a
          >
        </div>
        <!--end::Col-->
      </div>
      <!--end::Input group-->

      <!--begin::Input group-->
      <div class="row mb-7">
        <!--begin::Label-->
        <label class="col-lg-4 fw-bold text-muted">
          Country
          <i
            class="fas fa-exclamation-circle ms-1 fs-7"
            data-bs-toggle="tooltip"
            title="Country of origination"
          ></i>
        </label>
        <!--end::Label-->

        <!--begin::Col-->
        <div class="col-lg-8">
          <span class="fw-bolder fs-6 text-dark">Germany</span>
        </div>
        <!--end::Col-->
      </div>
      <!--end::Input group-->

      <!--begin::Input group-->
      <div class="row mb-7">
        <!--begin::Label-->
        <label class="col-lg-4 fw-bold text-muted">Communication</label>
        <!--end::Label-->

        <!--begin::Col-->
        <div class="col-lg-8">
          <span class="fw-bolder fs-6 text-dark">Email, Phone</span>
        </div>
        <!--end::Col-->
      </div>
      <!--end::Input group-->

      <!--begin::Input group-->
      <div class="row mb-10">
        <!--begin::Label-->
        <label class="col-lg-4 fw-bold text-muted">Allow Changes</label>
        <!--begin::Label-->

        <!--begin::Label-->
        <div class="col-lg-8">
          <span class="fw-bold fs-6">Yes</span>
        </div>
        <!--begin::Label-->
      </div>
      <!--end::Input group-->

      <div
        class="
          notice
          d-flex
          bg-light-warning
          rounded
          border-warning border border-dashed
          p-6
        "
      >
        <span class="svg-icon svg-icon-2tx svg-icon-warning me-4">
          <inline-svg src="media/icons/duotune/general/gen044.svg" />
        </span>
        <!--begin::Wrapper-->
        <div class="d-flex flex-stack flex-grow-1">
          <!--begin::Content-->
          <div class="fw-bold">
            <h4 class="text-gray-800 fw-bolder">We need your attention!</h4>

            <div class="fs-6 text-gray-600">
              Your payment was declined. To start using tools, please
              <a class="fw-bolder" href="#">Add Payment Method</a>.
            </div>
          </div>
          <!--end::Content-->
        </div>
        <!--end::Wrapper-->
      </div>
    </div>
    <!--end::Card body-->
  </div>
  <!--end::details View-->

  <!--begin::Row-->
  <div class="row gy-10 gx-xl-10">
    <!--begin::Col-->
    <div class="col-xl-6">
      <KTChartWidget1
        widget-classes="card-xxl-stretch mb-5 mb-xl-10"
      ></KTChartWidget1>
    </div>
    <!--end::Col-->

    <!--begin::Col-->
    <div class="col-xl-6">
      <KTListWidget1
        widget-classes="card-xxl-stretch mb-5 mb-xl-10'"
      ></KTListWidget1>
    </div>
    <!--end::Col-->
  </div>
  <!--end::Row-->

  <!--begin::Row-->
  <div class="row gy-10 gx-xl-10">
    <!--begin::Col-->
    <div class="col-xl-6">
      <KTListWidget5
        widget-classes="card-xxl-stretch mb-5 mb-xl-10"
      ></KTListWidget5>
    </div>
    <!--end::Col-->

    <!--begin::Col-->
    <div class="col-xl-6">
      <KTTableWidget5
        widget-classes="card-xxl-stretch mb-5 mb-xl-10"
      ></KTTableWidget5>
    </div>
    <!--end::Col-->
  </div>
  <!--end::Row-->
</template>

<script lang="ts">
import { defineComponent, onMounted } from "vue";
import KTChartWidget1 from "@/components/widgets/charts/Widget1.vue";
import KTListWidget5 from "@/components/widgets/lists/Widget5.vue";
import KTTableWidget5 from "@/components/widgets/tables/Widget5.vue";
import KTListWidget1 from "@/components/widgets/lists/Widget1.vue";
import { setCurrentPageBreadcrumbs } from "@/core/helpers/breadcrumb";

export default defineComponent({
  name: "account-overview",
  components: {
    KTChartWidget1,
    KTListWidget5,
    KTTableWidget5,
    KTListWidget1,
  },
  setup() {
    onMounted(() => {
      setCurrentPageBreadcrumbs("Overview", ["Account"]);
    });
  },
});
</script>
