// angular/demo1/src/app/_metronic/partials/content/cards/card4/card4.component.ts
import { Component, HostBinding, Input } from '@angular/core';

@Component({
  selector: 'app-card4',
  templateUrl: './card4.component.html',
})
export class Card4Component {
  @Input() icon: string = '';
  @Input() title: string = '';
  @Input() description: string = '';
  @HostBinding('class') class = 'card h-100';

  constructor() {}
}

<div
  class="card-body d-flex justify-content-center text-center flex-column p-8"
>
  <a class="text-gray-800 text-hover-primary d-flex flex-column cursor-pointer">
    <div class="symbol symbol-75px mb-6"><img [src]="icon" alt="" /></div>
    <div class="fs-5 fw-bolder mb-2">{{ title }}</div>
  </a>
  <div class="fs-7 fw-bold text-gray-400 mt-auto">{{ description }}</div>
</div>

// react/demo2/src/_metronic/partials/content/cards/Card4.tsx
/* eslint-disable jsx-a11y/anchor-is-valid */
import {FC} from 'react'
import {toAbsoluteUrl} from '../../../helpers'

type Props = {
  icon: string
  title: string
  description: string
}

const Card4: FC<Props> = ({icon, title, description}) => {
  return (
    <div className='card h-100'>
      <div className='card-body d-flex justify-content-center text-center flex-column p-8'>
        <a href='#' className='text-gray-800 text-hover-primary d-flex flex-column'>
          <div className='symbol symbol-75px mb-6'>
            <img src={toAbsoluteUrl(icon)} alt='' />
          </div>
          <div className='fs-5 fw-bolder mb-2'>{title}</div>
        </a>
        <div className='fs-7 fw-bold text-gray-400 mt-auto'>{description}</div>
      </div>
    </div>
  )
}

export {Card4}
