// angular/demo1/src/app/modules/wizards/steps/step4/step4.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Subscription } from 'rxjs';
import { ICreateAccount } from '../../create-account.helper';

@Component({
  selector: 'app-step4',
  templateUrl: './step4.component.html',
})
export class Step4Component implements OnInit {
  @Input('updateParentModel') updateParentModel: (
    part: Partial<ICreateAccount>,
    isFormValid: boolean
  ) => void;
  form: FormGroup;
  @Input() defaultValues: Partial<ICreateAccount>;

  private unsubscribe: Subscription[] = [];

  constructor(private fb: FormBuilder) {}

  ngOnInit() {
    this.initForm();
    this.updateParentModel({}, this.checkForm());
  }

  initForm() {
    this.form = this.fb.group({
      nameOnCard: [this.defaultValues.nameOnCard, [Validators.required]],
      cardNumber: [this.defaultValues.cardNumber, [Validators.required]],
      cardExpiryMonth: [
        this.defaultValues.cardExpiryMonth,
        [Validators.required],
      ],
      cardExpiryYear: [
        this.defaultValues.cardExpiryYear,
        [Validators.required],
      ],
      cardCvv: [this.defaultValues.cardCvv, [Validators.required]],
      saveCard: ['1'],
    });

    const formChangesSubscr = this.form.valueChanges.subscribe((val) => {
      this.updateParentModel(val, this.checkForm());
    });
    this.unsubscribe.push(formChangesSubscr);
  }

  checkForm() {
    return !(
      this.form.get('nameOnCard')?.hasError('required') ||
      this.form.get('cardNumber')?.hasError('required') ||
      this.form.get('cardExpiryMonth')?.hasError('required') ||
      this.form.get('cardExpiryYear')?.hasError('required') ||
      this.form.get('cardCvv')?.hasError('required')
    );
  }

  ngOnDestroy() {
    this.unsubscribe.forEach((sb) => sb.unsubscribe());
  }
}

<div class="pb-10 pb-lg-15">
  <h2 class="fw-bolder text-dark">Billing Details</h2>
  <div class="text-gray-400 fw-bold fs-6">
    If you need more info, please check out
    <a href="#" class="text-primary fw-bolder">Help Page</a>.
  </div>
</div>
<div [formGroup]="form">
  <div class="d-flex flex-column mb-7 fv-row">
    <label class="d-flex align-items-center fs-6 fw-bold form-label mb-2"
      ><span class="required">Name On Card</span
      ><i
        class="fas fa-exclamation-circle ms-2 fs-7"
        ngbTooltip="Specify a card holder's name"
      ></i></label
    ><input
      formControlName="nameOnCard"
      type="text"
      class="form-control form-control-solid"
      placeholder="Name on card"
    />
    <div
      class="fv-plugins-message-container invalid-feedback"
      *ngIf="
        form.get('nameOnCard')?.hasError('required') &&
        form.get('nameOnCard')?.touched
      "
    >
      Name on card is required
    </div>
  </div>
  <div class="d-flex flex-column mb-7 fv-row">
    <label class="required fs-6 fw-bold form-label mb-2">Card Number</label>
    <div class="position-relative">
      <input
        formControlName="cardNumber"
        type="text"
        class="form-control form-control-solid"
        placeholder="Enter card number"
      />
      <div
        class="fv-plugins-message-container invalid-feedback"
        *ngIf="
          form.get('cardNumber')?.hasError('required') &&
          form.get('cardNumber')?.touched
        "
      >
        Card number is required
      </div>
      <div class="position-absolute translate-middle-y top-50 end-0 me-5">
        <img
          src="./assets/media/svg/card-logos/visa.svg"
          alt=""
          class="h-25px"
        /><img
          src="./assets/media/svg/card-logos/mastercard.svg"
          alt=""
          class="h-25px"
        /><img
          src="./assets/media/svg/card-logos/american-express.svg"
          alt=""
          class="h-25px"
        />
      </div>
    </div>
  </div>
  <div class="row mb-10">
    <div class="col-md-8 fv-row">
      <label class="required fs-6 fw-bold form-label mb-2"
        >Expiration Date</label
      >
      <div class="row fv-row">
        <div class="col-6">
          <select
            formControlName="cardExpiryMonth"
            class="form-select form-select-solid"
          >
            <option></option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12">12</option>
          </select>
          <div
            class="fv-plugins-message-container invalid-feedback"
            *ngIf="
              form.get('cardExpiryMonth')?.hasError('required') &&
              form.get('cardExpiryMonth')?.touched
            "
          >
            Expiration month is required
          </div>
        </div>
        <div class="col-6">
          <select
            formControlName="cardExpiryYear"
            class="form-select form-select-solid"
          >
            <option></option>
            <option value="2021">2021</option>
            <option value="2022">2022</option>
            <option value="2023">2023</option>
            <option value="2024">2024</option>
            <option value="2025">2025</option>
            <option value="2026">2026</option>
            <option value="2027">2027</option>
            <option value="2028">2028</option>
            <option value="2029">2029</option>
            <option value="2030">2030</option>
            <option value="2031">2031</option>
          </select>
          <div
            class="fv-plugins-message-container invalid-feedback"
            *ngIf="
              form.get('cardExpiryYear')?.hasError('required') &&
              form.get('cardExpiryYear')?.touched
            "
          >
            Expiration year is required
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4 fv-row">
      <label class="d-flex align-items-center fs-6 fw-bold form-label mb-2"
        ><span class="required">CVV</span
        ><i
          class="fas fa-exclamation-circle ms-2 fs-7"
          ngbTooltip="Enter a card CVV code"
        ></i
      ></label>
      <div class="position-relative">
        <input
          formControlName="cardCvv"
          type="text"
          class="form-control form-control-solid"
          minlength="3"
          maxlength="4"
          placeholder="CVV"
        />
        <div
          class="fv-plugins-message-container invalid-feedback"
          *ngIf="
            form.get('cardCvv')?.hasError('required') &&
            form.get('cardCvv')?.touched
          "
        >
          CVV is required
        </div>
        <div class="position-absolute translate-middle-y top-50 end-0 me-3">
          <span
            class="svg-icon svg-icon-2hx"
            [inlineSVG]="'./assets/media/icons/duotune/finance/fin002.svg'"
          ></span>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex flex-stack">
    <div class="me-5">
      <label class="fs-6 fw-bold form-label"
        >Save Card for further billing?</label
      >
      <div class="fs-7 fw-bold text-gray-400">
        If you need more info, please check budget planning
      </div>
    </div>
    <label class="form-check form-switch form-check-custom form-check-solid"
      ><input
        formControlName="saveCard"
        class="form-check-input"
        type="checkbox"
        value="1"
      /><span class="form-check-label fw-bold text-gray-400"
        >Save Card</span
      ></label
    >
  </div>
</div>

// vue/demo2/src/components/wizard/steps/Step4.vue
<template>
  <!--begin::Wrapper-->
  <div class="w-100">
    <!--begin::Heading-->
    <div class="pb-10 pb-lg-15">
      <!--begin::Title-->
      <h2 class="fw-bolder text-dark">Billing Details</h2>
      <!--end::Title-->

      <!--begin::Notice-->
      <div class="text-gray-400 fw-bold fs-6">
        If you need more info, please check out
        <a href="#" class="text-primary fw-bolder">Help Page</a>.
      </div>
      <!--end::Notice-->
    </div>
    <!--end::Heading-->

    <div class="w-100">
      <!--begin::Input group-->
      <div class="d-flex flex-column mb-7 fv-row">
        <!--begin::Label-->
        <label class="d-flex align-items-center fs-6 fw-bold form-label mb-2">
          <span class="required">Name On Card</span>
          <i
            class="fas fa-exclamation-circle ms-2 fs-7"
            data-bs-toggle="tooltip"
            title="Specify a card holder's name"
          ></i>
        </label>
        <!--end::Label-->

        <Field
          type="text"
          class="form-control form-control-solid"
          placeholder=""
          name="nameOnCard"
        />
        <ErrorMessage
          class="fv-plugins-message-container invalid-feedback"
          name="nameOnCard"
        />
      </div>
      <!--end::Input group-->

      <!--begin::Input group-->
      <div class="d-flex flex-column mb-7 fv-row">
        <!--begin::Label-->
        <label class="required fs-6 fw-bold form-label mb-2">Card Number</label>
        <!--end::Label-->

        <!--begin::Input wrapper-->
        <div class="position-relative">
          <!--begin::Input-->
          <Field
            type="text"
            class="form-control form-control-solid"
            placeholder="Enter card number"
            name="cardNumber"
          />
          <ErrorMessage
            class="fv-plugins-message-container invalid-feedback"
            name="cardNumber"
          />
          <!--end::Input-->

          <!--begin::Card logos-->
          <div class="position-absolute translate-middle-y top-50 end-0 me-5">
            <img src="media/svg/card-logos/visa.svg" alt="" class="h-25px" />
            <img
              src="media/svg/card-logos/mastercard.svg"
              alt=""
              class="h-25px"
            />
            <img
              src="media/svg/card-logos/american-express.svg"
              alt=""
              class="h-25px"
            />
          </div>
          <!--end::Card logos-->
        </div>
        <!--end::Input wrapper-->
      </div>
      <!--end::Input group-->

      <!--begin::Input group-->
      <div class="row mb-10">
        <!--begin::Col-->
        <div class="col-md-8 fv-row">
          <!--begin::Label-->
          <label class="required fs-6 fw-bold form-label mb-2"
            >Expiration Date</label
          >
          <!--end::Label-->

          <!--begin::Row-->
          <div class="row fv-row">
            <!--begin::Col-->
            <div class="col-6">
              <Field
                name="cardExpiryMonth"
                class="form-select form-select-solid select2-hidden-accessible"
                placeholder="Month"
                as="select"
              >
                <option v-for="i in 12" :key="i" :label="i" :value="i"></option>
              </Field>
              <ErrorMessage
                class="fv-plugins-message-container invalid-feedback"
                name="cardExpiryMonth"
              />
            </div>
            <!--end::Col-->

            <!--begin::Col-->
            <div class="col-6">
              <Field
                name="cardExpiryYear"
                class="form-select form-select-solid select2-hidden-accessible"
                placeholder="Year"
                as="select"
              >
                <option
                  v-for="i in 10"
                  :key="i"
                  :label="i + (new Date().getFullYear() - 1)"
                  :value="i"
                ></option>
              </Field>
              <ErrorMessage
                class="fv-plugins-message-container invalid-feedback"
                name="cardExpiryYear"
              />
            </div>
            <!--end::Col-->
          </div>
          <!--end::Row-->
        </div>
        <!--end::Col-->

        <!--begin::Col-->
        <div class="col-md-4 fv-row">
          <!--begin::Label-->
          <label class="d-flex align-items-center fs-6 fw-bold form-label mb-2">
            <span class="required">CVV</span>
            <i
              class="fas fa-exclamation-circle ms-2 fs-7"
              data-bs-toggle="tooltip"
              title="Enter a card CVV code"
            ></i>
          </label>
          <!--end::Label-->

          <!--begin::Input wrapper-->
          <div class="position-relative">
            <!--begin::Input-->
            <Field
              type="text"
              class="form-control form-control-solid"
              minlength="3"
              maxlength="4"
              placeholder="CVV"
              name="cardCvv"
            />
            <ErrorMessage
              class="fv-plugins-message-container invalid-feedback"
              name="cardCvv"
            />
            <!--end::Input-->

            <!--begin::CVV icon-->
            <div class="position-absolute translate-middle-y top-50 end-0 me-3">
              <span class="svg-icon svg-icon-2hx">
                <inline-svg src="media/icons/duotune/finance/fin002.svg" />
              </span>
            </div>
            <!--end::CVV icon-->
          </div>
          <!--end::Input wrapper-->
        </div>
        <!--end::Col-->
      </div>
      <!--end::Input group-->

      <!--begin::Input group-->
      <div class="d-flex flex-stack">
        <!--begin::Label-->
        <div class="me-5">
          <label class="fs-6 fw-bold form-label"
            >Save Card for further billing?</label
          >
          <div class="fs-7 fw-bold text-gray-400">
            If you need more info, please check budget planning
          </div>
        </div>
        <!--end::Label-->

        <!--begin::Switch-->
        <label
          class="form-check form-switch form-check-custom form-check-solid"
        >
          <Field
            type="checkbox"
            class="form-check-input"
            name="saveCard"
            value="1"
          />
          <span class="form-check-label fw-bold text-gray-400">
            Save Card
          </span>
        </label>
        <!--end::Switch-->
      </div>
      <!--end::Input group-->
    </div>
  </div>
  <!--end::Wrapper-->
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { Field, ErrorMessage } from "vee-validate";

export default defineComponent({
  name: "step-4",
  components: {
    Field,
    ErrorMessage,
  },
});
</script>
