// react/demo2/src/app/modules/wizards/components/Horizontal.tsx
import React, {FC, useEffect, useRef, useState} from 'react'
import {Step1} from './steps/Step1'
import {Step2} from './steps/Step2'
import {Step3} from './steps/Step3'
import {Step4} from './steps/Step4'
import {Step5} from './steps/Step5'
import {KTSVG} from '../../../../_metronic/helpers'
import {StepperComponent} from '../../../../_metronic/assets/ts/components'
import {Formik, Form, FormikValues} from 'formik'
import {createAccountSchemas, ICreateAccount, inits} from './CreateAccountWizardHelper'

const Horizontal: FC = () => {
  const stepperRef = useRef<HTMLDivElement | null>(null)
  const stepper = useRef<StepperComponent | null>(null)
  const [currentSchema, setCurrentSchema] = useState(createAccountSchemas[0])
  const [initValues] = useState<ICreateAccount>(inits)

  const loadStepper = () => {
    stepper.current = StepperComponent.createInsance(stepperRef.current as HTMLDivElement)
  }

  const prevStep = () => {
    if (!stepper.current) {
      return
    }

    stepper.current.goPrev()

    setCurrentSchema(createAccountSchemas[stepper.current.currentStepIndex - 1])
  }

  const submitStep = (values: ICreateAccount, actions: FormikValues) => {
    if (!stepper.current) {
      return
    }

    setCurrentSchema(createAccountSchemas[stepper.current.currentStepIndex])

    if (stepper.current.currentStepIndex !== stepper.current.totatStepsNumber) {
      stepper.current.goNext()
    } else {
      stepper.current.goto(1)
      actions.resetForm()
    }
  }

  useEffect(() => {
    if (!stepperRef.current) {
      return
    }

    loadStepper()
  }, [stepperRef])

  return (
    <div className='card'>
      <div className='card-body'>
        <div
          ref={stepperRef}
          className='stepper stepper-links d-flex flex-column pt-15'
          id='kt_create_account_stepper'
        >
          <div className='stepper-nav mb-5'>
            <div className='stepper-item current' data-kt-stepper-element='nav'>
              <h3 className='stepper-title'>Account Type</h3>
            </div>

            <div className='stepper-item' data-kt-stepper-element='nav'>
              <h3 className='stepper-title'>Account Info</h3>
            </div>

            <div className='stepper-item' data-kt-stepper-element='nav'>
              <h3 className='stepper-title'>Business Info</h3>
            </div>

            <div className='stepper-item' data-kt-stepper-element='nav'>
              <h3 className='stepper-title'>Billing Details</h3>
            </div>

            <div className='stepper-item' data-kt-stepper-element='nav'>
              <h3 className='stepper-title'>Completed</h3>
            </div>
          </div>

          <Formik validationSchema={currentSchema} initialValues={initValues} onSubmit={submitStep}>
            {() => (
              <Form
                className='mx-auto mw-600px w-100 pt-15 pb-10'
                noValidate
                id='kt_create_account_form'
              >
                <div className='current' data-kt-stepper-element='content'>
                  <Step1 />
                </div>

                <div data-kt-stepper-element='content'>
                  <Step2 />
                </div>

                <div data-kt-stepper-element='content'>
                  <Step3 />
                </div>

                <div data-kt-stepper-element='content'>
                  <Step4 />
                </div>

                <div data-kt-stepper-element='content'>
                  <Step5 />
                </div>

                <div className='d-flex flex-stack pt-15'>
                  <div className='mr-2'>
                    <button
                      onClick={prevStep}
                      type='button'
                      className='btn btn-lg btn-light-primary me-3'
                      data-kt-stepper-action='previous'
                    >
                      <KTSVG
                        path='/media/icons/duotune/arrows/arr063.svg'
                        className='svg-icon-4 me-1'
                      />
                      Back
                    </button>
                  </div>

                  <div>
                    <button type='submit' className='btn btn-lg btn-primary me-3'>
                      <span className='indicator-label'>
                        {stepper.current?.currentStepIndex !==
                          stepper.current?.totatStepsNumber! - 1 && 'Continue'}
                        {stepper.current?.currentStepIndex ===
                          stepper.current?.totatStepsNumber! - 1 && 'Submit'}
                        <KTSVG
                          path='/media/icons/duotune/arrows/arr064.svg'
                          className='svg-icon-3 ms-2 me-0'
                        />
                      </span>
                    </button>
                  </div>
                </div>
              </Form>
            )}
          </Formik>
        </div>
      </div>
    </div>
  )
}

export {Horizontal}

// angular/demo1/src/app/modules/wizards/horizontal/horizontal.component.ts
import { Component, OnInit } from '@angular/core';
import { BehaviorSubject, Subscription } from 'rxjs';
import { ICreateAccount, inits } from '../create-account.helper';
@Component({
  selector: 'app-horizontal',
  templateUrl: './horizontal.component.html',
})
export class HorizontalComponent implements OnInit {
  formsCount = 5;
  account$: BehaviorSubject<ICreateAccount> =
    new BehaviorSubject<ICreateAccount>(inits);
  currentStep$: BehaviorSubject<number> = new BehaviorSubject(1);
  isCurrentFormValid$: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(
    false
  );
  private unsubscribe: Subscription[] = [];

  constructor() {}

  ngOnInit(): void {}

  updateAccount = (part: Partial<ICreateAccount>, isFormValid: boolean) => {
    const currentAccount = this.account$.value;
    const updatedAccount = { ...currentAccount, ...part };
    this.account$.next(updatedAccount);
    this.isCurrentFormValid$.next(isFormValid);
  };

  nextStep() {
    const nextStep = this.currentStep$.value + 1;
    if (nextStep > this.formsCount) {
      return;
    }
    this.currentStep$.next(nextStep);
  }

  prevStep() {
    const prevStep = this.currentStep$.value - 1;
    if (prevStep === 0) {
      return;
    }
    this.currentStep$.next(prevStep);
  }

  ngOnDestroy() {
    this.unsubscribe.forEach((sb) => sb.unsubscribe());
  }
}

<div class="card">
  <div class="card-body">
    <div
      class="stepper stepper-links d-flex flex-column pt-15"
      id="kt_create_account_stepper"
    >
      <div class="stepper-nav mb-5">
        <div
          class="stepper-item"
          [ngClass]="{
            current: currentStep$.value === 1,
            completed: currentStep$.value > 1
          }"
        >
          <h3 class="stepper-title">Account Type</h3>
        </div>

        <div
          class="stepper-item"
          [ngClass]="{
            current: currentStep$.value === 2,
            completed: currentStep$.value > 2
          }"
        >
          <h3 class="stepper-title">Account Info</h3>
        </div>

        <div
          class="stepper-item"
          [ngClass]="{
            current: currentStep$.value === 3,
            completed: currentStep$.value > 3
          }"
        >
          <h3 class="stepper-title">Business Info</h3>
        </div>

        <div
          class="stepper-item"
          [ngClass]="{
            current: currentStep$.value === 4,
            completed: currentStep$.value > 4
          }"
        >
          <h3 class="stepper-title">Billing Details</h3>
        </div>

        <div
          class="stepper-item"
          [ngClass]="{ current: currentStep$.value === 5 }"
        >
          <h3 class="stepper-title">Completed</h3>
        </div>
      </div>

      <form
        class="mx-auto mw-600px w-100 pt-15 pb-10"
        noValidate
        id="kt_create_account_form"
      >
        <div class="current">
          <ng-container *ngIf="currentStep$.value === 1">
            <app-step1
              class="w-100"
              [updateParentModel]="updateAccount"
              [defaultValues]="account$.value"
            ></app-step1>
          </ng-container>

          <ng-container *ngIf="currentStep$.value === 2">
            <app-step2
              class="w-100"
              [updateParentModel]="updateAccount"
              [defaultValues]="account$.value"
            ></app-step2>
          </ng-container>

          <ng-container *ngIf="currentStep$.value === 3">
            <app-step3
              class="w-100"
              [updateParentModel]="updateAccount"
              [defaultValues]="account$.value"
            ></app-step3>
          </ng-container>

          <ng-container *ngIf="currentStep$.value === 4">
            <app-step4
              class="w-100"
              [updateParentModel]="updateAccount"
              [defaultValues]="account$.value"
            ></app-step4>
          </ng-container>

          <ng-container *ngIf="currentStep$.value === 5">
            <app-step5 class="w-100"></app-step5>
          </ng-container>
        </div>

        <div class="d-flex flex-stack pt-15">
          <div class="mr-2">
            <ng-container *ngIf="currentStep$.value !== 1">
              <button
                type="button"
                class="btn btn-lg btn-light-primary me-3"
                (click)="prevStep()"
              >
                <span
                  [inlineSVG]="'./assets/media/icons/duotune/arrows/arr063.svg'"
                  class="svg-icon svg-icon-4 me-1"
                ></span>
                Back
              </button>
            </ng-container>
          </div>

          <ng-container *ngIf="currentStep$.value !== formsCount">
            <div>
              <button
                type="button"
                class="btn btn-lg btn-primary me-3"
                [disabled]="!isCurrentFormValid$.value"
                (click)="nextStep()"
              >
                <span class="indicator-label">
                  <ng-container *ngIf="currentStep$.value < formsCount - 1">
                    Continue {{ " " }}
                    <span
                      [inlineSVG]="
                        './assets/media/icons/duotune/arrows/arr064.svg'
                      "
                      class="svg-icon svg-icon-3 ms-2 me-0"
                    ></span>
                  </ng-container>
                  <ng-container *ngIf="currentStep$.value === formsCount - 1">
                    Submit
                  </ng-container>
                </span>
              </button>
            </div>
          </ng-container>
        </div>
      </form>
    </div>
  </div>
</div>
