// angular/demo1/src/app/modules/profile/connections/connections.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-connections',
  templateUrl: './connections.component.html',
})
export class ConnectionsComponent {
  constructor() {}
}

<div class="d-flex flex-wrap flex-stack mb-6">
  <h3 class="fw-bolder my-2">
    My Contacts
    <span class="fs-6 text-gray-400 fw-bold ms-1">(59)</span>
  </h3>

  <div class="d-flex my-2">
    <select
      name="status"
      data-control="select2"
      data-hide-search="true"
      class="form-select form-select-white form-select-sm w-125px"
    >
      <option value="Online" selected>Online</option>
      <option value="Pending">Pending</option>
      <option value="Declined">Declined</option>
      <option value="Accepted">Accepted</option>
    </select>
  </div>
</div>

<div class="row g-6 g-xl-9">
  <div class="col-md-6 col-xxl-4">
    <app-card3
      avatar="./assets/media/avatars/150-1.jpg"
      name="Emma Smith"
      job="Art Director"
      avgEarnings="$14,560"
      totalEarnings="$236,400"
    ></app-card3>
  </div>
  <div class="col-md-6 col-xxl-4">
    <app-card3
      color="danger"
      name="Melody Macy"
      job="Marketing Analytic"
      avgEarnings="$14,560"
      totalEarnings="$236,400"
      [online]="true"
    ></app-card3>
  </div>
  <div class="col-md-6 col-xxl-4">
    <app-card3
      avatar="./assets/media/avatars/150-2.jpg"
      name="Max Smith"
      job="Software Enginer"
      avgEarnings="$14,560"
      totalEarnings="$236,400"
    ></app-card3>
  </div>
  <div class="col-md-6 col-xxl-4">
    <app-card3
      avatar="./assets/media/avatars/150-4.jpg"
      name="Sean Bean"
      job="Web Developer"
      avgEarnings="$14,560"
      totalEarnings="$236,400"
    ></app-card3>
  </div>
  <div class="col-md-6 col-xxl-4">
    <app-card3
      avatar="./assets/media/avatars/150-15.jpg"
      name="Brian Cox"
      job="UI/UX Designer"
      avgEarnings="$14,560"
      totalEarnings="$236,400"
    ></app-card3>
  </div>
  <div class="col-md-6 col-xxl-4">
    <app-card3
      color="warning"
      name="Mikaela Collins"
      job="Head Of Marketing"
      avgEarnings="$14,560"
      totalEarnings="$236,400"
      [online]="true"
    ></app-card3>
  </div>
  <div class="col-md-6 col-xxl-4">
    <app-card3
      avatar="./assets/media/avatars/150-8.jpg"
      name="Francis Mitcham"
      job="Software Arcitect"
      avgEarnings="$14,560"
      totalEarnings="$236,400"
    ></app-card3>
  </div>
  <div class="col-md-6 col-xxl-4">
    <app-card3
      color="danger"
      name="Olivia Wild"
      job="System Admin"
      avgEarnings="$14,560"
      totalEarnings="$236,400"
      [online]="true"
    ></app-card3>
  </div>
  <div class="col-md-6 col-xxl-4">
    <app-card3
      color="primary"
      name="Neil Owen"
      job="Account Manager"
      avgEarnings="$14,560"
      totalEarnings="$236,400"
      [online]="true"
    ></app-card3>
  </div>
  <div class="col-md-6 col-xxl-4">
    <app-card3
      avatar="./assets/media/avatars/150-6.jpg"
      name="Dan Wilson"
      job="Web Desinger"
      avgEarnings="$14,560"
      totalEarnings="$236,400"
    ></app-card3>
  </div>
  <div class="col-md-6 col-xxl-4">
    <app-card3
      color="danger"
      name="Emma Bold"
      job="Corporate Finance"
      avgEarnings="$14,560"
      totalEarnings="$236,400"
      [online]="true"
    ></app-card3>
  </div>
  <div class="col-md-6 col-xxl-4">
    <app-card3
      avatar="./assets/media/avatars/150-7.jpg"
      name="Ana Crown"
      job="Customer Relationship"
      avgEarnings="$14,560"
      totalEarnings="$236,400"
    ></app-card3>
  </div>
</div>

<div class="d-flex flex-stack flex-wrap pt-10">
  <div class="fs-6 fw-bold text-gray-700">Showing 1 to 10 of 50 entries</div>

  <ul class="pagination">
    <li class="page-item previous">
      <a class="page-link cursor-pointer">
        <i class="previous"></i>
      </a>
    </li>

    <li class="page-item active">
      <a class="page-link cursor-pointer"> 1 </a>
    </li>

    <li class="page-item">
      <a class="page-link cursor-pointer"> 2 </a>
    </li>

    <li class="page-item">
      <a class="page-link cursor-pointer"> 3 </a>
    </li>

    <li class="page-item">
      <a class="page-link cursor-pointer"> 4 </a>
    </li>

    <li class="page-item">
      <a class="page-link cursor-pointer"> 5 </a>
    </li>

    <li class="page-item">
      <a class="page-link cursor-pointer"> 6 </a>
    </li>

    <li class="page-item next">
      <a class="page-link cursor-pointer">
        <i class="next"></i>
      </a>
    </li>
  </ul>
</div>

// vue/demo7/src/views/crafted/pages/profile/Connections.vue
<template>
  <!--begin::Followers toolbar-->
  <div class="d-flex flex-wrap flex-stack mb-6">
    <!--begin::Title-->
    <h3 class="fw-bolder my-2">
      My Connections
      <span class="fs-6 text-gray-400 fw-bold ms-1">(29)</span>
    </h3>
    <!--end::Title-->

    <!--begin::Controls-->
    <div class="d-flex my-2">
      <!--begin::Select-->
      <select
        name="status"
        data-control="select2"
        data-hide-search="true"
        class="form-select form-select-white form-select-sm w-125px"
      >
        <option value="Active" selected>Active</option>
        <option value="Approved">In Progress</option>
        <option value="Declined">To Do</option>
        <option value="In Progress">Completed</option>
      </select>
      <!--end::Select-->
    </div>
    <!--end::Controls-->
  </div>
  <!--end::Followers toolbar-->

  <!--begin::Row-->
  <div class="row g-6 mb-6 g-xl-9 mb-xl-9">
    <!--begin::Followers-->
    <Card3
      name="Patric Watson"
      position="Art Director at Novica Co."
      :online="true"
      avatar="media/avatars/150-12.jpg"
      :connected="true"
      avg-earnings="$14,560"
      total-sales="$236,400"
    ></Card3>

    <Card3
      name="Olivia Larson"
      position="Art Director at Seal Inc."
      :online="false"
      avatar="media/avatars/150-1.jpg"
      :connected="false"
      avg-earnings="$14,560"
      total-sales="$236,400"
    ></Card3>

    <Card3
      name="Adam Williams"
      position="System Arcitect at Wolto Co."
      :online="true"
      initials="A"
      color="warning"
      :connected="true"
      avg-earnings="$14,560"
      total-sales="$236,400"
    ></Card3>

    <Card3
      name="Paul Marcus"
      position="Art Director at Novica Co."
      :online="true"
      initials="P"
      color="primary"
      :connected="true"
      avg-earnings="$14,560"
      total-sales="$236,400"
    ></Card3>

    <Card3
      name="Neil Owen"
      position="Accountant at Numbers Co."
      :online="false"
      initials="N"
      color="success"
      :connected="false"
      avg-earnings="$14,560"
      total-sales="$236,400"
    ></Card3>

    <Card3
      name="Sean Paul"
      position="Developer at Loop Inc"
      :online="true"
      initials="S"
      color="info"
      :connected="false"
      avg-earnings="$14,560"
      total-sales="$236,400"
    ></Card3>

    <Card3
      name="Kitona Johnson"
      position="Web Designer at Nextop Ltd."
      :online="false"
      avatar="media/avatars/150-2.jpg"
      :connected="true"
      avg-earnings="$14,560"
      total-sales="$236,400"
    ></Card3>

    <Card3
      name="Robert Doe"
      position="Marketing Analytic at Avito Ltd."
      :online="false"
      avatar="media/avatars/150-11.jpg"
      :connected="false"
      avg-earnings="$14,560"
      total-sales="$236,400"
    ></Card3>

    <Card3
      name="Soul Jacob"
      position="Art Director at Novica Co."
      :online="false"
      avatar="media/avatars/150-7.jpg"
      :connected="false"
      avg-earnings="$14,560"
      total-sales="$236,400"
    ></Card3>

    <Card3
      name="Nina Strong"
      position="CTO at Kilp Ltd."
      :online="true"
      avatar="media/avatars/150-13.jpg"
      :connected="true"
      avg-earnings="$14,560"
      total-sales="$236,400"
    ></Card3>

    <Card3
      name="Patric Watson"
      position="Art Director at Novica Co."
      :online="true"
      avatar="media/avatars/150-12.jpg"
      :connected="false"
      avg-earnings="$14,560"
      total-sales="$236,400"
    ></Card3>

    <Card3
      name="Olivia Larson"
      position="Art Director at Seal Inc."
      :online="false"
      avatar="media/avatars/150-1.jpg"
      :connected="false"
      avg-earnings="$14,560"
      total-sales="$236,400"
    ></Card3>
    <!--end::Followers-->
  </div>
  <!--end::Row-->
</template>

<script lang="ts">
import { defineComponent, onMounted } from "vue";
import Card3 from "@/components/cards/Card3.vue";
import { setCurrentPageBreadcrumbs } from "@/core/helpers/breadcrumb";

export default defineComponent({
  name: "connections",
  components: {
    Card3,
  },
  setup() {
    onMounted(() => {
      setCurrentPageBreadcrumbs("Connections", ["Pages", "Profile"]);
    });
  },
});
</script>
