// angular/demo1/src/app/modules/errors/error500/error500.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-error500',
  templateUrl: './error500.component.html',
  styleUrls: ['./error500.component.scss']
})
export class Error500Component implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<h1 class="fw-bolder fs-4x text-gray-700 mb-10">System Error</h1>

<div class="fw-bold fs-3 text-gray-400 mb-15">
  Something went wrong! <br />
  Please try again later.
</div>

// react/demo2/src/app/modules/errors/components/Error500.tsx
import {FC} from 'react'

const Error500: FC = () => {
  return (
    <>
      <h1 className='fw-bolder fs-4x text-gray-700 mb-10'>System Error</h1>

      <div className='fw-bold fs-3 text-gray-400 mb-15'>
        Something went wrong! <br /> Please try again later.
      </div>
    </>
  )
}

export {Error500}
