// angular/demo1/src/app/modules/errors/error404/error404.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-error404',
  templateUrl: './error404.component.html',
  styleUrls: ['./error404.component.scss']
})
export class Error404Component implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<h1 class="fw-bolder fs-4x text-gray-700 mb-10">Page Not Found</h1>

<div class="fw-bold fs-3 text-gray-400 mb-15">
  The page you looked not found! <br />
  Plan your blog post by choosing a topic
</div>

// react/demo1/src/app/modules/errors/components/Error404.tsx
import {FC} from 'react'

const Error404: FC = () => {
  return (
    <>
      <h1 className='fw-bolder fs-4x text-gray-700 mb-10'>Page Not Found</h1>

      <div className='fw-bold fs-3 text-gray-400 mb-15'>
        The page you looked not found! <br /> Plan your blog post by choosing a topic
      </div>
    </>
  )
}

export {Error404}
