// theme/react/demo2/src/_metronic/_partials/widgets/tiles/TilesWidget10.js
/* eslint-disable jsx-a11y/anchor-is-valid */
import React from "react";

export function TilesWidget10({ className, widgetHeight = "175px" }) {
  return (
    <>
      <div
        className={`card card-custom ${className}`}
        style={{ height: widgetHeight }}
      >
        {/* begin::Body */}
        <div className="card-body d-flex align-items-center justify-content-between flex-wrap">
          <div className="mr-2">
            <h3 className="font-weight-bolder">Create CRM Reports</h3>
            <div className="text-dark-50 font-size-lg mt-2">
              Generate the latest CRM Report
            </div>
          </div>
          <a href="#" className="btn btn-primary font-weight-bold py-3 px-6">
            Start Now
          </a>
        </div>
        {/* end::Body */}
      </div>
    </>
  );
}

// theme/angular/demo1/src/app/_metronic/partials/content/widgets/tiles/tiles-widget10/tiles-widget10.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-tiles-widget10',
  templateUrl: './tiles-widget10.component.html',
})
export class TilesWidget10Component {
  @Input() cssClass = '';
  @Input() widgetHeight = '130px';

  constructor() { }
}

<!--begin::Mixed Widget 10-->
<div
  class="card card-custom"
  [ngClass]="cssClass"
  [ngStyle]="{ height: widgetHeight }"
>
  <!--begin::Body-->
  <div
    class="card-body d-flex align-items-center justify-content-between flex-wrap"
  >
    <div class="mr-2">
      <h3 class="font-weight-bolder">Create CRM Reports</h3>
      <div class="text-dark-50 font-size-lg mt-2">
        Generate the latest CRM Report
      </div>
    </div>
    <a href="#" class="btn btn-primary font-weight-bold py-3 px-6">Start Now</a>
  </div>
  <!--end::Body-->
</div>
<!--end::Mixed Widget 10-->
